### PR TITLE
Updating cmakelists in quokka to include microphysics

### PR DESCRIPTION
**Pull request by psharda**
Doesn't work at the moment, but I will work on it. Errors I get when doing `cmake ..` in `quokka/build`: 

python3: can't open file '/g/data1b/jh2/ps3459/quokka/util/build_scripts/write_probin.py': [Errno 2] No such file or directory

CMake Error at build/_deps/amrex-src/Src/CMakeLists.txt:11 (add_library):
  add_library cannot create target "amrex" because another target with the
  same name already exists.  The existing target is a static library created
  in source directory "/g/data1b/jh2/ps3459/quokka/extern/amrex/Src".  See
  documentation for policy CMP0002 for more details.

CMake Error at build/_deps/amrex-src/Src/CMakeLists.txt:13 (add_library):
  add_library cannot create ALIAS target "AMReX::amrex" because another
  target with the same name already exists.

CMake Error at build/_deps/amrex-src/Tools/CMake/AMReXFlagsTargets.cmake:67 (add_library):
  add_library cannot create target "Flags_CXX" because another target with
  the same name already exists.  The existing target is an interface library
  created in source directory "/g/data1b/jh2/ps3459/quokka/extern/amrex/Src".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  build/_deps/amrex-src/Src/CMakeLists.txt:42 (include)

CMake Error at extern/Microphysics/CMakeLists.txt:94 (add_subdirectory):
  add_subdirectory given source "/g/data1b/jh2/ps3459/quokka/unit_test" which
  is not an existing directory.

### CODE REVIEW

**Comment by psharda** [comment]
It's because CMAKE_SOURCE_DIR in Microphysics CMakeLists corresponds to quokka directory when called within quokka?

**Comment by BenWibking** [comment]
> It's because CMAKE_SOURCE_DIR in Microphysics CMakeLists corresponds to quokka directory when called within quokka?

Yeah, that's the issue.

**Comment by BenWibking** [comment]
The AMReX issue is because Quokka has already included AMReX. We need some way to disable Microphysics from including AMReX again when it's used by another code. It might be easiest to add a CMake option that's something like `BUILD_UNIT_TESTS` that when turned on, includes AMReX and includes the unit test subdirectory.

**Comment by psharda** [comment]
So, we don't want to build the unit test in Microphysics when building it with Quokka? If yes, then in the CMakeLists in Microphysics root, we insert an `ifdef` sort of loop, which, when turned on, links amrex and adds the unit test as a subdirectory?

**Comment by psharda** [comment]
Also, how should we specify the file paths in Microphysics such that when we link it to Quokka, Quokka can still find the relevant files? As in, what should we replace `CMAKE_SOURCE_DIR` with in the Microphysics CMakeLists such that it works with Quokka but also compiles by itself?

**Comment by BenWibking** [comment]
> So, we don't want to build the unit test in Microphysics when building it with Quokka? If yes, then in the CMakeLists in Microphysics root, we insert an `ifdef` sort of loop, which, when turned on, links amrex and adds the unit test as a subdirectory?

Yeah, that's what I would suggest. You can use the CMake `if` command (https://cmake.org/cmake/help/latest/command/if.html) along with a cached variable (https://hsf-training.github.io/hsf-training-cmake-webpage/05-variables/index.html#cached-variables).

**Comment by BenWibking** [comment]
> Also, how should we specify the file paths in Microphysics such that when we link it to Quokka, Quokka can still find the relevant files? As in, what should we replace `CMAKE_SOURCE_DIR` with in the Microphysics CMakeLists such that it works with Quokka but also compiles by itself?

In principle, relative paths should work (i.e., using the path relative to the location of CMakeLists.txt file in the directory tree). Does that work?

**Comment by psharda** [comment]
> > Also, how should we specify the file paths in Microphysics such that when we link it to Quokka, Quokka can still find the relevant files? As in, what should we replace `CMAKE_SOURCE_DIR` with in the Microphysics CMakeLists such that it works with Quokka but also compiles by itself?
> 
> In principle, relative paths should work (i.e., using the path relative to the location of CMakeLists.txt file in the directory tree). Does that work?

let me try

**Comment by psharda** [comment]
> > > Also, how should we specify the file paths in Microphysics such that when we link it to Quokka, Quokka can still find the relevant files? As in, what should we replace `CMAKE_SOURCE_DIR` with in the Microphysics CMakeLists such that it works with Quokka but also compiles by itself?
> > 
> > 
> > In principle, relative paths should work (i.e., using the path relative to the location of CMakeLists.txt file in the directory tree). Does that work?
> 
> let me try

What do we do with `CMAKE_BINARY_DIR`? Microphysics writes the file `extern_parameters.cpp` in `CMAKE_BINARY_DIR` based on the `write_probin.py` script, during compile time. If we compile Microphysics with Quokka, would Microphysics still be able to find `extern_parameters.cpp` that would be written in `Quokka/build`?

**Comment by BenWibking** [comment]
> What do we do with `CMAKE_BINARY_DIR`? Microphysics writes the file `extern_parameters.cpp` in `CMAKE_BINARY_DIR` based on the `write_probin.py` script, during compile time. If we compile Microphysics with Quokka, would Microphysics still be able to find `extern_parameters.cpp` that would be written in `Quokka/build`?

I think that should work as-is. As you point out, it will write it to quokka/build instead of quokka/extern/Microphysics/build, but that's fine.

**Comment by psharda** [comment]
Okay, now the Microphysics errors are gone while building quokka with `cmake`. The amrex errors remain, because I still need to add the `if` loop for amrex we talked about above.

**Comment by psharda** [comment]
I added two flags, one for amrex and one for unit test build. Now, quokka successfully builds with microphysics (if both flags are set to false, meaning, amrex is not built with microphysics and unit test is also not added). I am checking if it also compiles properly.

Why are all these tests below still failing?

**Comment by psharda** [comment]
Okay, quokka compiles successfully!

Test project /g/data1b/jh2/ps3459/quokka/build
      Start  1: ScalarAdvection
 1/24 Test  #1: ScalarAdvection ..................   Passed    9.34 sec
      Start  2: ScalarAdvectionSemiEllipse
 2/24 Test  #2: ScalarAdvectionSemiEllipse .......   Passed    2.23 sec
      Start  3: HydroContact
 3/24 Test  #3: HydroContact .....................   Passed    1.96 sec
      Start  4: HydroLeblanc
 4/24 Test  #4: HydroLeblanc .....................   Passed   18.80 sec
      Start  5: HydroShocktube
 5/24 Test  #5: HydroShocktube ...................   Passed    3.45 sec
      Start  6: ShuOsher
 6/24 Test  #6: ShuOsher .........................   Passed    6.54 sec
      Start  7: HydroSlowMovingShock
 7/24 Test  #7: HydroSlowMovingShock .............   Passed    2.34 sec
      Start  8: HydroVacuum
 8/24 Test  #8: HydroVacuum ......................   Passed    2.12 sec
      Start  9: HydroWave
 9/24 Test  #9: HydroWave ........................   Passed    2.23 sec
      Start 10: HydroHighMach
10/24 Test #10: HydroHighMach ....................   Passed    2.63 sec
      Start 11: RadForce
11/24 Test #11: RadForce .........................   Passed    5.41 sec
      Start 12: MarshakWave
12/24 Test #12: MarshakWave ......................   Passed    2.71 sec
      Start 13: MarshakWaveCGS
13/24 Test #13: MarshakWaveCGS ...................   Passed    2.08 sec
      Start 14: MatterEnergyExchange
14/24 Test #14: MatterEnergyExchange .............   Passed   26.06 sec
      Start 15: MatterEnergyExchangeRSLA
15/24 Test #15: MatterEnergyExchangeRSLA .........   Passed   13.96 sec
      Start 16: RadiationPulse
16/24 Test #16: RadiationPulse ...................   Passed    5.20 sec
      Start 17: RadiationStreaming
17/24 Test #17: RadiationStreaming ...............   Passed    2.01 sec
      Start 18: SuOlsonTest
18/24 Test #18: SuOlsonTest ......................   Passed    3.90 sec
      Start 19: RadiationPressureTube
19/24 Test #19: RadiationPressureTube ............   Passed    2.01 sec
      Start 20: RadhydroShock
20/24 Test #20: RadhydroShock ....................   Passed   15.10 sec
      Start 21: RadhydroShockCGS
21/24 Test #21: RadhydroShockCGS .................   Passed   15.97 sec
      Start 22: ODEIntegration
22/24 Test #22: ODEIntegration ...................   Passed    0.57 sec
      Start 23: PassiveScalar
23/24 Test #23: PassiveScalar ....................   Passed    3.59 sec
      Start 24: FCQuantities
24/24 Test #24: FCQuantities .....................   Passed    0.61 sec

100% tests passed, 0 tests failed out of 24

Total Test time (real) = 151.18 sec

**Comment by BenWibking** [comment]
> I added two flags, one for amrex and one for unit test build. Now, quokka successfully builds with microphysics (if both flags are set to false, meaning, amrex is not built with microphysics and unit test is also not added). I am checking if it also compiles properly.
> 
> Why are all these tests below still failing?

`BUILD_AMREX` needs to be set to false.

**Comment by psharda** [comment]
Should `BULD_UNIT_TEST` flag be also set to false by default?

**Comment by BenWibking** [comment]
> Should `BULD_UNIT_TEST` flag be also set to false by default?

Yeah, I think so.

**Comment by psharda** [comment]
@BenWibking, anything else that needs to be done, once the required tests pass?

**Review by BenWibking — APPROVED** [review]
This looks good to me.

**Pull request merged**
