### PR TITLE
random blast ISM problem

### PR DESCRIPTION
**Pull request by BenWibking**
This simulates the explosion of supernovae in a homogeneous ISM.

This problem is also added to the nightly regression test suite.

### CODE REVIEW

**Comment by BenWibking** [comment]
~~TODO: add compile-time option to use HLL solver.~~

**Review by markkrumholz — DISMISSED** [review]
Looks good.

**Comment by chongchonghe** [comment]
Why is this PR still open as it was approved a year ago?

**Comment by BenWibking** [comment]
> Why is this PR still open as it was approved a year ago?

I think what happened was there were immediately merge conflicts from another PR, and then I never got around to fixing those. It will have to be re-approved once those are fixed anyway.

**Comment by BenWibking** [comment]
HIP build failure:
```
In file included from /tmp/bwibking/_work/1/s/src/RandomBlast/blast.cpp:30:
/tmp/bwibking/_work/1/s/src/quadrature.hpp:46:9: error: no matching function for call to 'integrate'
        return quokka::math::quadrature::gauss<double, 7>::integrate(f, x0, x1);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/bwibking/_work/1/s/src/quadrature.hpp:38:64: note: in instantiation of function template specialization 'quad_1d<(lambda at /tmp/bwibking/_work/1/s/src/quadrature.hpp:38:72)>' requested here
        auto integrand = [=] AMREX_GPU_DEVICE(amrex::Real y) { return quad_1d([=] AMREX_GPU_DEVICE(amrex::Real x) { return f(x, y); }, x0, x1); };
                                                                      ^
/tmp/bwibking/_work/1/s/src/quadrature.hpp:30:10: note: in instantiation of function template specialization 'quad_2d<(lambda at /tmp/bwibking/_work/1/s/src/quadrature.hpp:30:18)>' requested here
                return quad_2d([=] AMREX_GPU_DEVICE(amrex::Real x, amrex::Real y) { return f(x, y, z); }, x0, x1, y0, y1);
                       ^
/tmp/bwibking/_work/1/s/src/RandomBlast/blast.cpp:154:35: note: in instantiation of function template specialization 'quad_3d<const (lambda at /tmp/bwibking/_work/1/s/src/RandomBlast/blast.cpp:128:15) &>' requested here
                                const Real weight = normfac * quad_3d(kern, x0, x0 + dx[0], y0, y0 + dx[1], z0, z0 + dx[2]);
                                                              ^
/tmp/bwibking/_work/1/s/src/gauss.hpp:639:50: note: candidate template ignored: substitution failure [with F = (lambda at /tmp/bwibking/_work/1/s/src/quadrature.hpp:38:72)]: no matching function for call to 'declval'
        template <class F> AMREX_GPU_DEVICE static auto integrate(F f, Real a, Real b, Real *pL1 = nullptr) -> decltype(std::declval<F>()(std::declval<Real>()))
                                                        ^                                                               ~~~
/tmp/bwibking/_work/1/s/src/gauss.hpp:611:50: note: candidate function template not viable: requires at most 2 arguments, but 3 were provided
        template <class F> AMREX_GPU_DEVICE static auto integrate(F f, Real *pL1 = nullptr) -> decltype(std::declval<F>()(std::declval<Real>()))
```

**Comment by BenWibking** [comment]
@markkrumholz This PR should finally be ready to merge again.

**Review by markkrumholz — APPROVED** [review]

**Pull request merged**
