### PR TITLE
build GitHub actions in parallel

### PR DESCRIPTION
**Pull request by BenWibking**
### Description
This changes the Github actions builds to build in parallel with 4 processes, since the Github actions VMs are now more powerful: https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/

The macOS actions runners are the same as before, so those should not be changed.

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [x] I have added a description (see above).
- [x] I have added a link to any related issues see (see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [ ] I have tested this PR on my local computer and all tests pass.
- [ ] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [ ] I have requested a reviewer for this PR.

### CODE REVIEW

**Comment by BenWibking** [comment]
The time for the Linux CMake build goes from ~70 min (1 process) to 50 min (2 processes) to 45 minutes (4 processes).

**Comment by psharda** [comment]
@BenWibking this doesn't matter for the azure pipelines right? I started the azure tests anyway.

**Comment by BenWibking** [comment]
> @BenWibking this doesn't matter for the azure pipelines right? I started the azure tests anyway.

Right, it doesn't affect those.

**Comment by BenWibking** [comment]
Looks like the GPU machines died again.

**Comment by BenWibking** [comment]
@psharda Can you approve?

**Comment by BenWibking** [comment]
@psharda all tests passed.

**Review by psharda — APPROVED** [review]

**Pull request merged**
