### PR TITLE
star cluster example

### PR DESCRIPTION
**Pull request by BenWibking**
This creates a StarCluster problem that initializes a spherical gas cloud with sinusoidal velocity perturbations that can then collapse under its own gravity.

Uses an isothermal EOS. No other physics is included.

### CODE REVIEW

**Comment by BenWibking** [comment]
It currently crashes inside the multigrid solver with:
```
MPI initialized with 8 MPI processes
MPI initialized with thread support level 0
AMReX (22.12-19-gae58672b451d) initialized
Using default ref_ratio = 2 at all levels
Successfully read inputs file ... 
Generating velocity perturbations...
rms dv = 2.171488262
Writing checkpoint chk00000
Writing plotfile plt00000

Coarse STEP 1 at t = 0 (0%) starts ...
        >> Using global timestep on this coarse step (estimated work ratio: 1).
[Level 0 step 1] ADVANCE with time = 0 dt = 0.00277215369
[Level 0 step 1] Advanced 262144 cells
[Level 1 step 1] ADVANCE with time = 0 dt = 0.00277215369
[Level 1 step 1] Advanced 2097152 cells
Doing Poisson solve...

terminate called after throwing an instance of 'std::runtime_error'
  what():  Assertion `m_grids[amrlev][0].coarsenable(m_amr_ref_ratio[amrlev-1])' failed, file "/home/benwibking.linux/quokka/extern/amrex/Src/LinearSolvers/MLMG/AMReX_MLLinOp.H", line 1077, Msg: "MLLinOp: grids not coarsenable between AMR levels"
terminate called after throwing an instance of 'terminate called after throwing an instance of 'std::runtime_error'
  what():  Assertion `m_grids[amrlev][0].coarsenable(m_amr_ref_ratio[amrlev-1])' failed, file "/home/benwibking.linux/quokka/extern/amrex/Src/LinearSolvers/MLMG/AMReX_MLLinOp.H", line 1077, Msg: "MLLinOp: grids not coarsenable between AMR levels"
terminate called after throwing an instance of 'std::runtime_error'
  what():  Assertion `m_grids[amrlev][0].coarsenable(m_amr_ref_ratio[amrlev-1])' failed, file "/home/benwibking.linux/quokka/extern/amrex/Src/LinearSolvers/MLMG/AMReX_MLLinOp.H", line 1077, Msg: "MLLinOp: grids not coarsenable between AMR levels"
terminate called after throwing an instance of 'std::runtime_error'
  what():  Assertion `m_grids[amrlev][0].coarsenable(m_amr_ref_ratio[amrlev-1])' failed, file "/home/benwibking.linux/quokka/extern/amrex/Src/LinearSolvers/MLMG/AMReX_MLLinOp.H", line 1077, Msg: "MLLinOp: grids not coarsenable between AMR levels"
[lima-fedora:482917] *** Process received signal ***
[lima-fedora:482917] Signal: Aborted (6)
[lima-fedora:482917] Signal code:  (-6)
terminate called after throwing an instance of 'std::runtime_error'
```

**Comment by WeiqunZhang** [comment]
Looks like level 1 completely covers level 0, because the number of cells on level 1 is 8 times that on level 0.  It is still supposed to work even in this case.

**Comment by BenWibking** [comment]
> Looks like level 1 completely covers level 0, because the number of cells on level 1 is 8 times that on level 0. It is still supposed to work even in this case.

It works, but only when max_level = 1. If I increase max_level further, then the assertion is triggered.

**Review by markkrumholz — DISMISSED** [review]

**Review by markkrumholz — APPROVED** [review]

**Comment by psharda** [comment]
Superseded by #342

**Pull request closed without merging**
