### PR TITLE
Fix build on Cray systems

### LINKED ISSUE #315: turn object library into a static library?
If it is possible turn `QuokkaObj` into a static library, it should avoid the linking issues that are causing the build to fail on Setonix: https://github.com/quokka-astro/quokka/issues/309.

### PR DESCRIPTION
**Pull request by psharda**
Fixes #315

### CODE REVIEW

**Comment by BenWibking** [comment]
I'll have to test this manually on Frontier and Setonix.

**Comment by BenWibking** [comment]
Hmm, did not work:
```
[100%] Linking CXX executable test_hydro3d_blast
cd /software/projects/pawsey0807/bwibking/quokka/build/src/HydroBlast3D && /software/setonix/2022.11/software/cray-sles15-zen3/cce-14.0.3/cmake-3.21.4-ymvmfd3uqczbwigjs5mpzhbx32swzxw2/bin/cmake -E cmake_link_script CMakeFiles/test_hydro3d_blast.dir/link.txt --verbose=1
/opt/cray/pe/craype/2.7.17/bin/CC -I/software/projects/pawsey0807/bwibking/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/hip-5.2.3-vq7ca5zqqlhqtkcgr5bz5w37qivdk6jc/include -O3 -DNDEBUG -fgpu-rdc CMakeFiles/test_hydro3d_blast.dir/test_hydro3d_blast.cpp.o -o test_hydro3d_blast  -Wl,-rpath,/software/projects/pawsey0807/bwibking/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/hip-5.2.3-vq7ca5zqqlhqtkcgr5bz5w37qivdk6jc/lib:/software/projects/pawsey0807/bwibking/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/rocrand-5.2.3-6znfq2srlrn4i2vrzysodutpnw5ujnee/lib -lstdc++fs ../../amrex/Src/libamrex_3d.a ../../fmt/libfmt.a ../libQuokkaObj.a -lstdc++fs ../../amrex/Src/libamrex_3d.a /software/projects/pawsey0807/bwibking/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/hip-5.2.3-vq7ca5zqqlhqtkcgr5bz5w37qivdk6jc/lib/libamdhip64.so.5.2.21153 --hip-link --offload-arch=gfx90a /software/projects/pawsey0807/bwibking/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/llvm-amdgpu-5.2.3-cstlr4a7qbugix6tk5n755szxdpdlufh/lib/clang/14.0.0/lib/linux/libclang_rt.builtins-x86_64.a /software/projects/pawsey0807/bwibking/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/rocrand-5.2.3-6znfq2srlrn4i2vrzysodutpnw5ujnee/lib/libhiprand.so.1.1 /software/projects/pawsey0807/bwibking/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/rocrand-5.2.3-6znfq2srlrn4i2vrzysodutpnw5ujnee/lib/librocrand.so.1.1 ../../fmt/libfmt.a
Warning: Cannot find all neccessary path for loaded rocm version!!!
error: Linking globals named '_ZN5amrex5Arena10align_sizeE': symbol multiply defined!
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

libamrex_3d.a is linked twice.

**Comment by BenWibking** [comment]
The problem is this part:
```
 -lstdc++fs ../../amrex/Src/libamrex_3d.a ../../fmt/libfmt.a ../libQuokkaObj.a -lstdc++fs ../../amrex/Src/libamrex_3d.a
 ```

**Comment by BenWibking** [comment]
Ok, so this is fixable if we use `target_link_libraries` with the `PUBLIC` keyword. Unfortunately, this requires re-writing how all test problems are compiled so as to use `target_link_libraries`...

**Comment by psharda** [comment]
> The problem is this part:
> 
> ```
>  -lstdc++fs ../../amrex/Src/libamrex_3d.a ../../fmt/libfmt.a ../libQuokkaObj.a -lstdc++fs ../../amrex/Src/libamrex_3d.a
> ```

why does -lstdc++ link amrex_3d.a twice?

**Comment by psharda** [comment]
> Ok, so this is fixable if we use `target_link_libraries` with the `PUBLIC` keyword. Unfortunately, this requires re-writing how all test problems are compiled so as to use `target_link_libraries`...

just for QuokkaObj or for all of these too:

```
link_libraries(AMReX::amrex)
link_libraries(fmt::fmt)
link_libraries(hdf5::hdf5)
```

**Comment by BenWibking** [comment]
> > Ok, so this is fixable if we use `target_link_libraries` with the `PUBLIC` keyword. Unfortunately, this requires re-writing how all test problems are compiled so as to use `target_link_libraries`...
> 
> just for QuokkaObj or for all of these too:
> 
> ```
> link_libraries(AMReX::amrex)
> link_libraries(fmt::fmt)
> link_libraries(hdf5::hdf5)
> ```

Possibly all of them, I'm not sure. I think there are two options: i) link all of the test problems with `target_link_libraries`, or ii) revert to the way we compiled it before using QuokkaObj. The latter seems easier to me.

**Comment by BenWibking** [comment]
For option i), I think you could add all of the `target_link_libraries` calls inside a `setup_target(...)` convenience function, similar to the `setup_target_for_microphysics_compilation` function that you created.

**Comment by BenWibking** [comment]
> > The problem is this part:
> > ```
> >  -lstdc++fs ../../amrex/Src/libamrex_3d.a ../../fmt/libfmt.a ../libQuokkaObj.a -lstdc++fs ../../amrex/Src/libamrex_3d.a
> > ```
> 
> why does -lstdc++ link amrex_3d.a twice?

This refers to two separate libraries: `stdc++` and `amrex_3d.a`. The `-l` flag just indicates a different way to find the library.

**Comment by psharda** [comment]
> > > Ok, so this is fixable if we use `target_link_libraries` with the `PUBLIC` keyword. Unfortunately, this requires re-writing how all test problems are compiled so as to use `target_link_libraries`...
> > 
> > 
> > just for QuokkaObj or for all of these too:
> > ```
> > link_libraries(AMReX::amrex)
> > link_libraries(fmt::fmt)
> > link_libraries(hdf5::hdf5)
> > ```
> 
> Possibly all of them, I'm not sure. I think there are two options: i) link all of the test problems with `target_link_libraries`, or ii) revert to the way we compiled it before using QuokkaObj. The latter seems easier to me.

Have you tried option ii on Frontier and Setonix? Did it work?

**Comment by BenWibking** [comment]
I haven't tested either solution on Setonix.

**Comment by psharda** [comment]
> I haven't tested either solution on Setonix.

I will push a commit that basically removes `QuokkaObj`, but only tests for primordial chem + one extra test. Maybe you can try it on Setonix and see if it builds? If it does, I will then remove `QuokkaObj` from all other tests too.

**Comment by psharda** [comment]
@BenWibking can you try building the latest version of this branch on Frontier and Setonix?

**Comment by BenWibking** [comment]
It builds successfully on Setonix.

**Comment by BenWibking** [comment]
Are you able to build it on Setonix?

**Comment by BenWibking** [comment]
Ah ok, I am only able to build if I apply the patch to extern/Microphysics/CMakeLists.txt that I posted in the Slack channel.

**Comment by psharda** [comment]
> Ah ok, I am only able to build if I apply the patch to extern/Microphysics/CMakeLists.txt that I posted in the Slack channel.

Which patch?

**Comment by BenWibking** [comment]
> 

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3a67c399..c9acbc28 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -13,48 +13,8 @@ find_package (Python COMPONENTS Interpreter Development)
 find_package(Threads)

 include(CTest)
-
-add_library(Microphysics SHARED) # initialized below
-
-#----------------------------------------------------------------------------------------------------------------------
-# mylib sources
-#----------------------------------------------------------------------------------------------------------------------
-
-set(sources
-    EOS/eos_composition.H
-    integration/integrator.H
-    integration/integrator_data.H
-    integration/integrator_rhs_strang.H
-    integration/integrator_type_strang.H
-    interfaces/ArrayUtilities.H
-    interfaces/burner.H
-    interfaces/burn_type.H
-    interfaces/eos.H
-    interfaces/eos_data.H
-    interfaces/eos_type.H
-    interfaces/eos_override.H
-    interfaces/network.H
-    interfaces/rhs_type.H
-    networks/rate_type.H
-    networks/rhs.H
-    unit_test/unit_test.H)
-
-#----------------------------------------------------------------------------------------------------------------------
-# mylib target
-#----------------------------------------------------------------------------------------------------------------------
-
 include(CMakePackageConfigHelpers)

-target_sources(Microphysics PUBLIC ${sources})
-#below line will add NAUX_NET and STRANG compiler flags
-#these are needed for preprocessor variables
-target_compile_definitions(Microphysics PUBLIC NAUX_NET STRANG)
-
-set_target_properties(Microphysics PROPERTIES
-    SOVERSION ${PROJECT_VERSION_MAJOR}
-    VERSION ${PROJECT_VERSION}
-    LINKER_LANGUAGE CXX)
-
 #we need to have extern_parameters.cpp be available at configure time
 #the script write_probin.py writes this .cpp file so we call it here
 #note, execute_process only works on 'cmake' and not 'make'
```

**Comment by psharda** [comment]
So we don't build Microphysics as a target by itself? We still need the stuff you deleted above to compile Microphysics as a standalone target (outside of quokka) so I can wrap up this up in `if(BUILD_UNIT_TEST)`

**Comment by BenWibking** [comment]
> So we don't build Microphysics as a target by itself? We still need the stuff you deleted above to compile Microphysics as a standalone target (outside of quokka) so I can wrap up this up in `if(BUILD_UNIT_TEST)`

Why is it necessary to build `libMicrophysics`? I thought that was just left over from the first attempt at building with CMake before we switched to just adding the source files directly to the targets.

**Comment by psharda** [comment]
> -target_compile_definitions(Microphysics PUBLIC NAUX_NET STRANG)

https://github.com/AMReX-Astro/Microphysics/pull/1217 should help.

We just need the preprocessor directives `NAUX_NET` and `STRANG`

**Comment by psharda** [comment]
> Are you able to build it on Setonix?

I can build on Setonix but the tests don't run?

```
[100%] Built target test_advection
[100%] Built target test_primordial_chem
psharda@setonix-02:~/quokka/build> ctest
Test project /home/psharda/quokka/build
    Start 1: PrimordialChem
1/2 Test #1: PrimordialChem ...................***Exception: SegFault  1.42 sec
    Start 2: ScalarAdvection
2/2 Test #2: ScalarAdvection ..................***Failed    0.35 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =   1.79 sec

The following tests FAILED:
	  1 - PrimordialChem (SEGFAULT)
	  2 - ScalarAdvection (Failed)
Errors while running CTest

```

**Comment by BenWibking** [comment]
You have to run on the GPU nodes

**Comment by psharda** [comment]
Do you have a PBS script to run on Setonix GPUs?

**Comment by BenWibking** [comment]
There's one located at `scripts/setonix-1node.submit`.

**Comment by BenWibking** [comment]
You'll need to edit it with the name of your executable and input file. Then you can just run
```
sbatch scripts/setonix-1node.submit
```

**Comment by psharda** [comment]
You have to specify each test and its input file one by one?

```
## run
EXE="build/src/HydroBlast3D/test_hydro3d_blast"
INPUTS="tests/benchmark_unigrid_512.in"
```

Can you not run all tests together, like we do on Gadi or avatar GPUs, using `ninja test`?

**Comment by BenWibking** [comment]
> You have to specify each test and its input file one by one?
> 
> ```
> ## run
> EXE="build/src/HydroBlast3D/test_hydro3d_blast"
> INPUTS="tests/benchmark_unigrid_512.in"
> ```
> 
> Can you not run all tests together, like we do on Gadi or avatar GPUs, using `ninja test`?

Oh sure, you can do that too. This was just an example with production sims in mind, rather than running the test suite.

**Comment by psharda** [comment]
Cool. So I just need to replace 

```
## run
EXE="build/src/HydroBlast3D/test_hydro3d_blast"
INPUTS="tests/benchmark_unigrid_512.in"
```

by `ninja test`

**Comment by psharda** [comment]
oh lol that doesn't work. how do you run all tests together on setonix

**Comment by BenWibking** [comment]
> Cool. So I just need to replace
> 
> ```
> ## run
> EXE="build/src/HydroBlast3D/test_hydro3d_blast"
> INPUTS="tests/benchmark_unigrid_512.in"
> ```
> 
> by `ninja test`

Replace
https://github.com/quokka-astro/quokka/blob/6194feb05750602233433f6e051616b0ee2b29e6/scripts/setonix-1node.submit#L45
with 
```
     ninja test"
```

**Comment by psharda** [comment]
Wait, but I have been using `cmake -C ../cmake/setonix.cmake ..` so this won't work on setonix GPUs no?

**Comment by BenWibking** [comment]
> Wait, but I have been using `cmake -C ../cmake/setonix.cmake ..` so this won't work on setonix GPUs no?

I don't follow... The SLURM script doesn't affect the build steps in any way.

**Comment by psharda** [comment]
> > Wait, but I have been using `cmake -C ../cmake/setonix.cmake ..` so this won't work on setonix GPUs no?
> 
> I don't follow... The SLURM script doesn't affect the build steps in any way.

I still get build.ninja errors when I replace `${EXE} ${INPUTS}" ` with `ninja test " `

```
ninja: error: loading 'build.ninja': No such file or directory
ninja: error: loading 'build.ninja': No such file or directory
ninja: error: loading 'build.ninja': No such file or directory
ninja: error: loading 'build.ninja': No such file or directory
ninja: error: loading 'build.ninja': No such file or directory
ninja: error: loading 'build.ninja': No such file or directory
ninja: error: loading 'build.ninja': No such file or directory
ninja: error: loading 'build.ninja': No such file or directory
srun: error: nid002882: tasks 0-7: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=2391078.0

```

**Comment by BenWibking** [comment]
Did you set `-GNinja` as one of the CMake options? Otherwise, CMake generates a Makefile and you have to do `make test` instead.

**Comment by psharda** [comment]
No that's what I meant earlier; I just used `cmake -C ../cmake/setonix.cmake ..` without modifying the setonix.cmake file

**Comment by BenWibking** [comment]
> No that's what I meant earlier; I just used `cmake -C ../cmake/setonix.cmake ..` without modifying the setonix.cmake file

Ah ok. Then you have to do `make test` or `ctest`.

**Pull request closed without merging**
