### PR TITLE
output 2D slice plotfiles

### LINKED ISSUE #237: add output plotfiles with a 2D slice through the data
See https://github.com/AMReX-Combustion/PelePhysics/blob/b5e6bbf1eed1382ea29a1a5a85fd640ec36f7b67/Utility/Diagnostics/DiagFramePlane.cpp for an example of how to do this.

### PR DESCRIPTION
**Pull request by BenWibking**
### Description
Output 2D slices of the simulation as AMReX plotfiles. The implementation is adaped from PeleLMeX ([documentation](https://amrex-combustion.github.io/PeleLMeX/manual/html/LMeXControls.html#run-time-diagnostics)).

It can be turned on for any variables (including derived variables) with runtime parameters, e.g.:
```
quokka.diagnostics = slice_z           # Space-separated name(s) of diagnostics (arbitrary)
quokka.slice_z.type = DiagFramePlane   # Diagnostic type (others may be added in the future)
quokka.slice_z.file = slicez_plt       # Output file prefix (should end in "plt")
quokka.slice_z.normal = 2              # Plane normal (0 == x, 1 == y, 2 == z)
quokka.slice_z.center = 2.4688e20      # Coordinate in the normal direction
quokka.slice_z.int    = 10             # Output interval (in number of coarse steps)
quokka.slice_z.interpolation = Linear  # Interpolation type: Linear or Quadratic (default: Linear)

# The problem must output these derived variable(s)
derived_vars = temperature
# List of variables to include in output
quokka.slice_z.field_names = gasDensity gasInternalEnergy temperature
```

### Related issues
Closes https://github.com/quokka-astro/quokka/issues/237.

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [x] I have added a description (see above).
- [x] I have added a link to any related issues see (see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [x] I have tested this PR on my local computer and all tests pass.
- [x] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [x] I have requested a reviewer for this PR.

### CODE REVIEW

**Review by markkrumholz — DISMISSED** [review]

**Review by markkrumholz — DISMISSED** [review]

**Comment by BenWibking** [comment]
@markkrumholz all of the clang-tidy warnings are (hopefully) fixed now. can you re-approve?

**Review by markkrumholz — APPROVED** [review]

**Pull request merged**
