### PR TITLE
treat all compiler warnings as errors

### PR DESCRIPTION
**Pull request by BenWibking**
This turns on `-Werror` when compiling the CI tests. This means that the code must compile without warnings to pass the CI tests.

### CODE REVIEW

**Comment by BenWibking** [comment]
@psharda This line is causing the CI to fail: https://github.com/psharda/Microphysics/blob/main/EOS/primordial_chem/actual_eos.H#L164 because there is a potential uninitialized use on lines 257, 258, and 261.

Can you initialize `temp`, `dens`, and `eint` to `NAN`?

**Comment by psharda** [comment]
> @psharda This line is causing the CI to fail: https://github.com/psharda/Microphysics/blob/main/EOS/primordial_chem/actual_eos.H#L164 because there is a potential uninitialized use on lines 257, 258, and 261.
> 
> Can you initialize `temp`, `dens`, and `eint` to `NAN`?

Done. But the error seemed to come from HydroShocktubeCMA test, which doesn't use this file; it uses gamma_law/actual_eos.H: https://github.com/quokka-astro/quokka/actions/runs/4962088034/jobs/8879707458?pr=280

**Comment by BenWibking** [comment]
Depends on https://github.com/AMReX-Astro/Microphysics/pull/1186.

**Comment by psharda** [comment]
@BenWibking one GPU test failed.

**Comment by BenWibking** [comment]
It looks like a CMake bug, sigh. (https://gitlab.kitware.com/cmake/cmake/-/issues/22541)

**Comment by BenWibking** [comment]
I will figure out a workaround.

**Comment by BenWibking** [comment]
> It looks like a CMake bug, sigh. (https://gitlab.kitware.com/cmake/cmake/-/issues/22541)

Sorry, I mean CMake "feature" :)

**Comment by BenWibking** [comment]
I've disabled the warnings-as-errors option for the GPU build. This should catch all warnings produced when doing a CPU-only build on all platforms, but will not catch a warning that _only_ appears when building for GPU. This is still a significant improvement on the current state of the code, which ignores warnings in all cases.

**Review by psharda — APPROVED** [review]

**Pull request merged**
