### PR TITLE
enforce code formatting

### PR DESCRIPTION
**Pull request by BenWibking**
This adds a configuration file for the `pre-commit` tool that causes it to run `clang-format` on all code changed in a pull request. When [pre-commit.ci](https://pre-commit.ci/) is also used, it will automatically format code in pull requests to match the style specified in `src/.clang-format`.

### CODE REVIEW

**Review by markkrumholz — DISMISSED** [review]
Going to approve this just because I don't know the yaml format well enough to tell if this is sensible. I am therefore going to just trust you Ben. ;-)

**Comment by BenWibking** [comment]
> Going to approve this just because I don't know the yaml format well enough to tell if this is sensible. I am therefore going to just trust you Ben. ;-)

Ok, that works for me. I've made it so every PR requires a review to be merged, but I may change the settings to disable that for PRs like this.

**Comment by BenWibking** [comment]
@markkrumholz The pre-commit-ci bot re-formatted all the code and deleted your old approval. This will force us to always follow the style mandated by `src/.clang-format` from now on. If this works for you, can you re-approve this PR?

**Review by markkrumholz — APPROVED** [review]
Wow, that's a lot of reformatting. I'm going to assume the bot is written well enough that all that has happened here is that spacing has been fixed, since I'm not going to do a line-by-line check on this!

**Pull request merged**
