### PR TITLE
add axis-aligned projection outputs

### PR DESCRIPTION
**Pull request by BenWibking**
This outputs 2D axis-aligned projections as AMReX plotfiles prefixed with `proj`.

The problem generator must call `computePlaneProjection(F const &user_f, const int dir)` where `user_f` is a lambda function that returns the value to project and `dir` is the axis along which the projection is taken.

### CODE REVIEW

**Review by markkrumholz — COMMENTED** [review]
It looks like this code only products projection plots on the coarsest level. I assume that this is the intended option, but it does somewhat limit the utility for a problem that uses any significant degree of AMR. It might make more sense to project to the finest level, or give the user an option to do so. Fine if you don't want to tackle that in this PR and save it for a future enhancement, in which case I will approve now.

**Comment by BenWibking** [comment]
> It looks like this code only products projection plots on the coarsest level. I assume that this is the intended option, but it does somewhat limit the utility for a problem that uses any significant degree of AMR. It might make more sense to project to the finest level, or give the user an option to do so. Fine if you don't want to tackle that in this PR and save it for a future enhancement, in which case I will approve now.

Yes, that is a significant limitation of the current PR. It's good enough for my cloud simulations, though, so I'd prefer to leave that to a future PR.

**Review by markkrumholz — DISMISSED** [review]

**Comment by BenWibking** [comment]
@markkrumholz This needs to be re-approved because I had to do a manual merge commit.

**Review by markkrumholz — DISMISSED** [review]

**Comment by BenWibking** [comment]
@markkrumholz There was another merge issue. Can you approve again? Hopefully it works this time.

**Review by markkrumholz — APPROVED** [review]

**Pull request merged**
