### PR TITLE
add uniform cooling box test

### PR DESCRIPTION
**Pull request by BenWibking**
This adds a cooling test with tabulated cooling for a uniform box of gas. This can be used to test the tabulated cooling machinery in isolation from hydrodynamics.

### CODE REVIEW

**Review by markkrumholz — COMMENTED** [review]
The test itself loosk fine, but calling the problem test_box is a bit non-descriptive. Maybe change to test_cooling_amr or something like that?

**Comment by BenWibking** [comment]
> The test itself loosk fine, but calling the problem test_box is a bit non-descriptive. Maybe change to test_cooling_amr or something like that?

Ok, that makes sense. What about `test_cooling_onezone`?

**Comment by markkrumholz** [comment]
> > The test itself loosk fine, but calling the problem test_box is a bit non-descriptive. Maybe change to test_cooling_amr or something like that?
> 
> Ok, that makes sense. What about `test_cooling_onezone`?

Yes, that name sounds fine.

**Comment by BenWibking** [comment]
I don't think there's a use case for this test anymore. Closing for now.

**Pull request closed without merging**
