### PR TITLE
Define advecting pulse test problem.

### PR DESCRIPTION
**Pull request by chongchonghe**
### Description
Defined the advecting pulse test problem (Krumholz+2007). This test gives exactly the same result (visually) as in CASTRO II paper and consistent result between non-advecting and advecting case, demonstrating the code's ability to resolve diffusion limit as well as capture radiation advection in this limit.

Notes:
- Based on Add-O(beta-tau)-terms branch

### Checklist

- [x] I have added a description (see above).
- [x] I have added a link to any related issues see (see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [x] I have added tests for any new physics that this PR adds to the code.
- [x] I have tested this PR on my local computer and all tests pass.
- [x] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [x] I have requested a reviewer for this PR.

### CODE REVIEW

**Comment by chongchonghe** [comment]
Almost ready for merging after [Add-O(beta-tau)-terms](https://github.com/quokka-astro/quokka/tree/Add-O(beta-tau)-terms) is accepted. Before merging, I need to think about a more robust way to validate the result. Currently, I compare the solutions in advecting and non-advecting cases visually and confirm they are consistent. However, to make it more convincing, we need to compare the shifted advecting result with the non-advecting result in one figure. @BenWibking What's your idea on how to achieve this? Is it possible to run a simulation with v=0 via `sim.evolve()`, copy the result, then reset the initial condition with v>0, and run it again, in the same cpp file?

**Comment by chongchonghe** [comment]
> Almost ready for merging after [Add-O(beta-tau)-terms](https://github.com/quokka-astro/quokka/tree/Add-O(beta-tau)-terms) is accepted. Before merging, I need to think about a more robust way to validate the result. Currently, I compare the solutions in advecting and non-advecting cases visually and confirm they are consistent. However, to make it more convincing, we need to compare the shifted advecting result with the non-advecting result in one figure. @BenWibking What's your idea on how to achieve this? Is it possible to run a simulation with v=0 via `sim.evolve()`, copy the result, then reset the initial condition with v>0, and run it again, in the same cpp file?

As I think about it, this is probably not necessary. Radiation advection is strictly tested in the RadhydroUniformAdvecting test, so there is no need to validate it here. Since there is no analytic solution to this problem (as we are aware of), we can just keep it as it is. 

So, ready to merge after `Add-O(beta-tau)-terms` branch is merged.

**Comment by BenWibking** [comment]
> Almost ready for merging after [Add-O(beta-tau)-terms](https://github.com/quokka-astro/quokka/tree/Add-O(beta-tau)-terms) is accepted. Before merging, I need to think about a more robust way to validate the result. Currently, I compare the solutions in advecting and non-advecting cases visually and confirm they are consistent. However, to make it more convincing, we need to compare the shifted advecting result with the non-advecting result in one figure. @BenWibking What's your idea on how to achieve this? Is it possible to run a simulation with v=0 via `sim.evolve()`, copy the result, then reset the initial condition with v>0, and run it again, in the same cpp file?

Yes, this is possible. You can create a new `sim` object and run a new simulation after the first one is done. Then you can copy the final state from both and compare them. That would be the best way to do this, in my opinion.

**Comment by BenWibking** [comment]
I think this PR is merging into the wrong branch... it says: "[chongchonghe](https://github.com/chongchonghe) wants to merge 4 commits into [Add-O(beta-tau)-terms](https://github.com/quokka-astro/quokka/tree/Add-O(beta-tau)-terms) from [advecting_pulse_test_new](https://github.com/quokka-astro/quokka/tree/advecting_pulse_test_new)"

Do you mean to merge this into `development` instead?

**Comment by chongchonghe** [comment]
> I think this PR is merging into the wrong branch... it says: "[chongchonghe](https://github.com/chongchonghe) wants to merge 4 commits into [Add-O(beta-tau)-terms](https://github.com/quokka-astro/quokka/tree/Add-O(beta-tau)-terms) from [advecting_pulse_test_new](https://github.com/quokka-astro/quokka/tree/advecting_pulse_test_new)"
> 
> 
> 
> Do you mean to merge this into `development` instead?

OK, same as the other one. I'll fix it.

**Comment by chongchonghe** [comment]
It seems like the nvcc compilation failed because of recent AMReX update.

**Comment by BenWibking** [comment]
It looks like there's a timeout failure on moth: https://dev.azure.com/quokka-code/quokka-CI/_build/results?buildId=7786&view=logs&j=0410d313-00ef-550d-37c8-facbf7a1cb10&t=62d0f0fc-52cd-5dfc-847e-751a25f0b5e6

and a possible hardware failure on avatargpue: https://dev.azure.com/quokka-code/quokka-CI/_build/results?buildId=7783&view=logs&j=655dacad-9e02-5f72-e0cf-043ebfb7cecc&t=040ddf27-e411-58f7-ab97-dfe1d2a20f3a

**Comment by chongchonghe** [comment]
OK. The RadhydroPulse test takes way too long to run in 3D on GPU, so I have to turn it off. I keep it on only when compiled with 1D. I'll test it with 3D GPU on gadi manually and ensure it gives the right result. 

/azp run

**Comment by BenWibking** [comment]
It looks like there's an instability present in the non-advecting velocity (see below), but that can be fixed in a separate PR.
[radhydro_pulse_velocity.pdf](https://github.com/quokka-astro/quokka/files/13850510/radhydro_pulse_velocity.pdf)

**Review by BenWibking — APPROVED** [review]
LGTM

**Pull request merged**
