### PR TITLE
reorganize source code into subdirectories

### PR DESCRIPTION
**Pull request by BenWibking**
### Description
The code used to be simple, but now it's not. I've reorganized all of the source code files under `src/` into subdirectories (one level only).

Unfortunately, virtually every file had to be changed in order to update header include paths. No other changes were made to the code (other than file renaming).

The new `src/` directory layout is as follows:
```console
$ tree -d .
.
├── chemistry
├── cooling
├── hydro
├── io
├── linear_advection
├── math
├── particles
├── problems
│   ├── Advection
│   ├── Advection2D
│   ├── AdvectionSemiellipse
│   ├── BinaryOrbitCIC
│   ├── Cooling
│   ├── FCQuantities
│   ├── HydroBlast2D
│   ├── HydroBlast3D
│   ├── HydroContact
│   ├── HydroHighMach
│   ├── HydroKelvinHelmholz
│   ├── HydroLeblanc
│   ├── HydroQuirk
│   ├── HydroRichtmeyerMeshkov
│   ├── HydroShocktube
│   ├── HydroShocktubeCMA
│   ├── HydroShuOsher
│   ├── HydroSMS
│   ├── HydroVacuum
│   ├── HydroWave
│   ├── NSCBC
│   ├── ODEIntegration
│   ├── PassiveScalar
│   ├── PopIII
│   ├── PrimordialChem
│   ├── RadBeam
│   ├── RadForce
│   ├── RadhydroBB
│   ├── RadhydroPulse
│   ├── RadhydroPulseDyn
│   ├── RadhydroPulseGrey
│   ├── RadhydroPulseMGconst
│   ├── RadhydroPulseMGint
│   ├── RadhydroShell
│   ├── RadhydroShock
│   ├── RadhydroShockCGS
│   ├── RadhydroShockMultigroup
│   ├── RadhydroUniformAdvecting
│   ├── RadMarshak
│   ├── RadMarshakAsymptotic
│   ├── RadMarshakCGS
│   ├── RadMarshakVaytet
│   ├── RadMatterCoupling
│   ├── RadMatterCouplingRSLA
│   ├── RadPulse
│   ├── RadShadow
│   ├── RadStreaming
│   ├── RadStreamingY
│   ├── RadSuOlson
│   ├── RadTophat
│   ├── RadTube
│   ├── RandomBlast
│   ├── RayleighTaylor2D
│   ├── RayleighTaylor3D
│   ├── ShockCloud
│   ├── SphericalCollapse
│   └── StarCluster
├── radiation
├── turbulence
└── util
```

### Related issues
N/A

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [x] I have added a description (see above).
- [x] I have added a link to any related issues see (see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [x] I have tested this PR on my local computer and all tests pass.
- [x] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [x] I have requested a reviewer for this PR.

### CODE REVIEW

**Comment by BenWibking** [comment]
@chongchonghe Can you review?

**Comment by markkrumholz** [comment]
I can look tomorrow. Currently in transit — greetings from SFO. --Mark KrumholzTyped on a tiny keyboardOn Jul 28, 2024, at 4:07 PM, Ben Wibking ***@***.***> wrote:﻿
@chongchonghe Can you review?

**Comment by chongchonghe** [comment]
I will take a look after lunch. 

I love this idea to reorganize the test problems into one folder and sort the source code into categories. I wanted to do that a long time ago.

**Review by chongchonghe — APPROVED** [review]

**Pull request merged**
