### PR TITLE
Fix cray build systems

### LINKED ISSUE #309: can't build with CCE + ROCm
ROCm 5.0 can't build the latest AMReX due to a compiler bug. Since this is the version provided on Setonix, this means we can't currently build Quokka on Setonix.

Per Weiqun, we need to ask Setonix staff to install ROCm 5.2.

### PR DESCRIPTION
**Pull request by psharda**
Continuation of #316.

Fixes https://github.com/quokka-astro/quokka/issues/309.

### CODE REVIEW

**Comment by psharda** [comment]
This is my setonix log:

```
quokka>> source scripts/setonix.profile
quokka>> cd build
build>> cmake -C ../cmake/setonix.cmake ..
```

it builds fine. this is my PBS script:

```
#!/bin/bash

#SBATCH -A pawsey0807-gpu
#SBATCH -J quokka_benchmark
#SBATCH -o 1node_%x-%j.out
#SBATCH -t 00:10:00
#SBATCH -p gpu
#SBATCH --exclusive
#SBATCH --ntasks-per-node=8
#SBATCH --gpus-per-node=8
#SBATCH --cpus-per-task=8
##SBATCH --core-spec=8
#SBATCH -N 1

# load modules
module load craype-accel-amd-gfx90a
module load rocm/5.0.2

# this environment setting is currently needed to work-around a
# known issue with Libfabric
export FI_MR_CACHE_MAX_COUNT=0  # libfabric disable caching

# always run with GPU-aware MPI
export MPICH_GPU_SUPPORT_ENABLED=1

# use correct NIC-to-GPU binding
export MPICH_OFI_NIC_POLICY=NUMA

## run
#EXE="build/src/HydroBlast3D/test_hydro3d_blast"
#INPUTS="tests/benchmark_unigrid_512.in"

srun bash -c "
    case \$((SLURM_LOCALID)) in
      0) GPU=4;;
      1) GPU=5;;
      2) GPU=2;;
      3) GPU=3;;
      4) GPU=6;;
      5) GPU=7;;
      6) GPU=0;;
      7) GPU=1;;
    esac
    export ROCR_VISIBLE_DEVICES=\$((GPU));
    ctest"
```

but the tests fail with error:

```
Output:
----------------------------------------------------------
MPICH ERROR [Rank 0] [job id ] [Sat Jun 17 15:52:08 2023] [nid002942] - Abort(1091855) (rank 0 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(170):
MPID_Init(441).......:
MPIR_pmi_init(83)....: PMI2_Job_GetId returned 14

```

What am I missing ?
The same build also fails on GPUs, when I use `-G Ninja` in cmake, and replace `ctest` with `ninja test` in the PBS script

**Comment by BenWibking** [comment]
That's odd. I think it is not working because `ctest` tries to run multiple subprocesses that aren't directly launched with `srun`, which is a complication I hadn't thought about.

I think the easiest workaround is to just run the test problems individually. If that won't work, then I can try to figure out a better workaround.

**Comment by BenWibking** [comment]
I've thought about this a bit more. I think for running `ctest`, the job script should look more like Example 1 here: https://support.pawsey.org.au/documentation/display/US/Setonix+GPU+Partition+Quick+Start#SetonixGPUPartitionQuickStart-ExampleJobscripts.

I'm still not sure how launching with `srun` affects `ctest`.

**Comment by BenWibking** [comment]
When I run the PrimordialChem problem manually, I get:
```
MPI initialized with 8 MPI processes
MPI initialized with thread support level 0
Initializing HIP...
HIP initialized with 8 devices.
AMReX (23.05-31-g2e1106e246c4) initialized
srun: error: nid002856: tasks 0-7: Floating point exception
srun: launch/slurm: _step_signal: Terminating StepId=2398805.0
```

**Comment by BenWibking** [comment]
> When I run the PrimordialChem problem manually, I get:
> 
> ```
> MPI initialized with 8 MPI processes
> MPI initialized with thread support level 0
> Initializing HIP...
> HIP initialized with 8 devices.
> AMReX (23.05-31-g2e1106e246c4) initialized
> srun: error: nid002856: tasks 0-7: Floating point exception
> srun: launch/slurm: _step_signal: Terminating StepId=2398805.0
> ```

I think it would make sense to fix this in a separate PR.

**Comment by psharda** [comment]
I don't get this error, but I get a different error:

```
MPICH ERROR [Rank 0] [job id �] [Sun Jun 18 15:55:40 2023] [nid002086] - Abort(1091855) (rank 0 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(170):
MPID_Init(441).......:
MPIR_pmi_init(83)....: PMI2_Job_GetId returned 14

srun: error: nid002086: tasks 0-7: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=2401782.0
```

I copied `setonix-1node.submit` in my `build` directory, and gave:

```
## run
EXE="src/PrimordialChem/test_primordial_chem"
INPUTS="../tests/primordial_chem.in"
```
which are relative to the `build` directory

**Comment by BenWibking** [comment]
> I don't get this error, but I get a different error:
> 
> ```
> MPICH ERROR [Rank 0] [job id �] [Sun Jun 18 15:55:40 2023] [nid002086] - Abort(1091855) (rank 0 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
> MPIR_Init_thread(170):
> MPID_Init(441).......:
> MPIR_pmi_init(83)....: PMI2_Job_GetId returned 14
> 
> srun: error: nid002086: tasks 0-7: Exited with exit code 1
> srun: launch/slurm: _step_signal: Terminating StepId=2401782.0
> ```
> 
> I copied `setonix-1node.submit` in my `build` directory, and gave:
> 
> ```
> ## run
> EXE="src/PrimordialChem/test_primordial_chem"
> INPUTS="../tests/primordial_chem.in"
> ```
> 
> which are relative to the `build` directory

That is a very weird error. I have never seen that before. If you re-submit it, does it still happen again?

**Comment by psharda** [comment]
Yup. My build directory is `/home/psharda/quokka/build`; dont think you can access it?

Why is Setonix so weird?

**Comment by BenWibking** [comment]
> Yup. My build directory is `/home/psharda/quokka/build`; dont think you can access it?
> 
> Why is Setonix so weird?

Sigh...

This shouldn't matter, but can you try building it your $MYSOFTWARE directory? You should be able to just `cd $MYSOFTWARE` to get to it.

**Comment by psharda** [comment]
Tried that. Same error.

Note that I am using `cmake` to build quokka, without the `-GNinja` option, so building it for CPUs. From the setonix PBS script, it looks like the queue I am submitting the job to is for GPUs? Could that be the problem?

^ tried building with `-GNinja`. Same error still.

**Comment by BenWibking** [comment]
> Tried that. Same error.
> 
> Note that I am using `cmake` to build quokka, without the `-GNinja` option, so building it for CPUs. From the setonix PBS script, it looks like the queue I am submitting the job to is for GPUs? Could that be the problem?
> 
> ^ tried building with `-GNinja`. Same error still.

`-GNinja` doesn't change whether it's build for CPU or GPU. If you are using `setonix.cmake`, then it is building for GPUs:

https://github.com/quokka-astro/quokka/blob/6194feb05750602233433f6e051616b0ee2b29e6/cmake/setonix.cmake#L6

**Comment by psharda** [comment]
What do we do? I didn't think building on Setonix would be a problem given that we can build quokka on other systems.

**Comment by BenWibking** [comment]
Can you try cloning a fresh copy and re-building, and then running the script from the root quokka directory with `sbatch scripts/setonix-1node.submit`? I am not able to reproduce the error you see.

**Comment by BenWibking** [comment]
Can you apply the following patch and try it again?

```
diff --git a/cmake/setonix.cmake b/cmake/setonix.cmake
index 0fbe122..5574a11 100644
--- a/cmake/setonix.cmake
+++ b/cmake/setonix.cmake
@@ -1,11 +1,8 @@
 # host configuration
 # run with `cmake -C host_config.cmake ..` from inside build directory

-set(CMAKE_C_COMPILER "cc" CACHE PATH "")
-set(CMAKE_CXX_COMPILER "CC" CACHE PATH "")
 set(AMReX_GPU_BACKEND HIP CACHE STRING "")
 set(AMReX_AMD_ARCH gfx90a CACHE STRING "") # MI250X
-set(AMREX_GPUS_PER_NODE 8 CACHE STRING "")
 set(AMReX_ASCENT OFF BOOL STRING "")

 option(QUOKKA_PYTHON ON)
diff --git a/scripts/setonix-1node.submit b/scripts/setonix-1node.submit
index 2fa0569..424eb6b 100644
--- a/scripts/setonix-1node.submit
+++ b/scripts/setonix-1node.submit
@@ -27,8 +27,8 @@ export MPICH_GPU_SUPPORT_ENABLED=1
 export MPICH_OFI_NIC_POLICY=NUMA

 ## run
-EXE="build/src/HydroBlast3D/test_hydro3d_blast"
-INPUTS="tests/benchmark_unigrid_512.in"
+EXE="build/src/PrimordialChem/test_primordial_chem"
+INPUTS="tests/primordial_chem.in"

 srun bash -c "
     case \$((SLURM_LOCALID)) in
```

**Comment by BenWibking** [comment]
Actually, I have a better idea. Can you copy my whole quokka directory `/software/projects/pawsey0807/bwibking/quokka` to your $MYSOFTWARE? Then run `sbatch scripts/setonix-1node.submit` and see if we get the same results.

**Comment by psharda** [comment]
> Actually, I have a better idea. Can you copy my whole quokka directory `/software/projects/pawsey0807/bwibking/quokka` to your $MYSOFTWARE? Then run `sbatch scripts/setonix-1node.submit` and see if we get the same results.

I still gotta `source scripts/setonix.profile` first right, or does the pbs script set up the required modules on the compute node

**Comment by BenWibking** [comment]
> > Actually, I have a better idea. Can you copy my whole quokka directory `/software/projects/pawsey0807/bwibking/quokka` to your $MYSOFTWARE? Then run `sbatch scripts/setonix-1node.submit` and see if we get the same results.
> 
> I still gotta `source scripts/setonix.profile` first right, or does the pbs script set up the required modules on the compute node

I would source scripts/setonix.profile just in case.

**Comment by psharda** [comment]
Same error. Look at `/software/projects/pawsey0807/psharda/quokka/1node_quokka_benchmark-2422143.out`

**Comment by BenWibking** [comment]
> Same error. Look at `/software/projects/pawsey0807/psharda/quokka/1node_quokka_benchmark-2422143.out`

Ok, something is definitely broken on Setonix.

Can you open a help ticket, explaining that you have copied the build that worked successfully for me, but fails when you submit a job using the exact same binary and jobscript?  Feel free to add me and Mark to the ticket as well.

**Comment by BenWibking** [comment]
This is still definitely a bug, but can you try modifying the jobscript as follows and see if it works:
```
diff --git a/scripts/setonix-1node.submit b/scripts/setonix-1node.submit
index 2fa0569..cc313d5 100644
--- a/scripts/setonix-1node.submit
+++ b/scripts/setonix-1node.submit
@@ -27,10 +27,10 @@ export MPICH_GPU_SUPPORT_ENABLED=1
 export MPICH_OFI_NIC_POLICY=NUMA

 ## run
-EXE="build/src/HydroBlast3D/test_hydro3d_blast"
-INPUTS="tests/benchmark_unigrid_512.in"
+EXE="build/src/PrimordialChem/test_primordial_chem"
+INPUTS="tests/primordial_chem.in"

-srun bash -c "
+srun --mpi=cray_shasta bash -c "
     case \$((SLURM_LOCALID)) in
       0) GPU=4;;
       1) GPU=5;;
```

The only difference from before should be changing `srun` to `srun --mpi=cray_shasta`.

**Comment by BenWibking** [comment]
This doesn't seem to make a difference for this issue (I've tested both and I get the same floating point exception error), but I've added a new bash script to use a newer version of the ROCm compiler: https://github.com/quokka-astro/quokka/pull/321.

**Comment by psharda** [comment]
> /software/projects/pawsey0807/psharda/quokka/

Didn't work. Submitted a ticket.

**Comment by BenWibking** [comment]
Ok, I get the same floating point exception error with ROCm 5.0.2, 5.3.0, and 5.4.3:

```
MPI initialized with 8 MPI processes
MPI initialized with thread support level 0
Initializing HIP...
HIP initialized with 8 devices.
AMReX (23.05-31-g2e1106e246c4) initialized
srun: error: nid002876: tasks 0-7: Floating point exception
srun: launch/slurm: _step_signal: Terminating StepId=2422746.0
```

**Comment by psharda** [comment]
The build on cray systems will be fixed by #311 now. 
The setonix build still fails, but continuing from our conversation on Slack @BenWibking , we can close this PR.

**Pull request closed without merging**
