### PR TITLE
quokka::EOS code linting

### PR DESCRIPTION
**Pull request by BenWibking**
### Description
This fixes some clang-tidy and CodeQL warnings for EOS.hpp. All of the changes convert pass-by-value to pass-by-reference for large objects in EOS function calls.

### Related issues
https://github.com/quokka-astro/quokka/security/code-scanning/2609

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [x] I have added a description (see above).
- [x] I have added a link to any related issues see (see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [x] I have tested this PR on my local computer and all tests pass.
- [x] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [x] I have requested a reviewer for this PR.

### CODE REVIEW

**Comment by BenWibking** [comment]
Oops, the change in function signature breaks some radiation test problems. I'll fix those.

**Comment by BenWibking** [comment]
Apparently clang-tidy is confused. These warnings are all wrong. The parameter names are all already commented out.
```
{'DiagnosticName': 'misc-unused-parameters', 'DiagnosticMessage': {'Message': "parameter 'massScalars' is unused", 'FilePath': '/github/workspace/src/RadMarshak/test_radiation_marshak.cpp', 'FileOffset': 2943, 'Replacements': [{'FilePath': '/github/workspace/src/RadMarshak/test_radiation_marshak.cpp', 'Offset': 2943, 'Length': 1, 'ReplacementText': ' /*massScalars*/'}]}, 'Level': 'Warning', 'BuildDirectory': '/github/workspace/build/src/RadMarshak'}, 
{'DiagnosticName': 'misc-unused-parameters', 'DiagnosticMessage': {'Message': "parameter 'massScalars' is unused", 'FilePath': '/github/workspace/src/RadMarshak/test_radiation_marshak.cpp', 'FileOffset': 3240, 'Replacements': [{'FilePath': '/github/workspace/src/RadMarshak/test_radiation_marshak.cpp', 'Offset': 3240, 'Length': 1, 'ReplacementText': ' /*massScalars*/'}]}, 'Level': 'Warning', 'BuildDirectory': '/github/workspace/build/src/RadMarshak'}, 
{'DiagnosticName': 'misc-unused-parameters', 'DiagnosticMessage': {'Message': "parameter 'massScalars' is unused", 'FilePath': '/github/workspace/src/RadMarshakCGS/test_radiation_marshak_cgs.cpp', 'FileOffset': 3194, 'Replacements': [{'FilePath': '/github/workspace/src/RadMarshakCGS/test_radiation_marshak_cgs.cpp', 'Offset': 3194, 'Length': 1, 'ReplacementText': ' /*massScalars*/'}]}, 'Level': 'Warning', 'BuildDirectory': '/github/workspace/build/src/RadMarshakCGS'}, 
{'DiagnosticName': 'misc-unused-parameters', 'DiagnosticMessage': {'Message': "parameter 'massScalars' is unused", 'FilePath': '/github/workspace/src/RadMarshakCGS/test_radiation_marshak_cgs.cpp', 'FileOffset': 3497, 'Replacements': [{'FilePath': '/github/workspace/src/RadMarshakCGS/test_radiation_marshak_cgs.cpp', 'Offset': 3497, 'Length': 1, 'ReplacementText': ' /*massScalars*/'}]}, 'Level': 'Warning', 'BuildDirectory': '/github/workspace/build/src/RadMarshakCGS'}, 
{'DiagnosticName': 'misc-unused-parameters', 'DiagnosticMessage': {'Message': "parameter 'massScalars' is unused", 'FilePath': '/github/workspace/src/RadMatterCoupling/test_radiation_matter_coupling.cpp', 'FileOffset': 2958, 'Replacements': [{'FilePath': '/github/workspace/src/RadMatterCoupling/test_radiation_matter_coupling.cpp', 'Offset': 2958, 'Length': 1, 'ReplacementText': ' /*massScalars*/'}]}, 'Level': 'Warning', 'BuildDirectory': '/github/workspace/build/src/RadMatterCoupling'}, 
{'DiagnosticName': 'misc-unused-parameters', 'DiagnosticMessage': {'Message': "parameter 'massScalars' is unused", 'FilePath': '/github/workspace/src/RadMatterCouplingRSLA/test_radiation_matter_coupling_rsla.cpp', 'FileOffset': 3055, 'Replacements': [{'FilePath': '/github/workspace/src/RadMatterCouplingRSLA/test_radiation_matter_coupling_rsla.cpp', 'Offset': 3055, 'Length': 1, 'ReplacementText': ' /*massScalars*/'}]}, 'Level': 'Warning', 'BuildDirectory': '/github/workspace/build/src/RadMatterCouplingRSLA'}, 
{'DiagnosticName': 'misc-unused-parameters', 'DiagnosticMessage': {'Message': "parameter 'massScalars' is unused", 'FilePath': '/github/workspace/src/RadSuOlson/test_radiation_SuOlson.cpp', 'FileOffset': 3334, 'Replacements': [{'FilePath': '/github/workspace/src/RadSuOlson/test_radiation_SuOlson.cpp', 'Offset': 3334, 'Length': 1, 'ReplacementText': ' /*massScalars*/'}]}, 'Level': 'Warning', 'BuildDirectory': '/github/workspace/build/src/RadSuOlson'}, 
{'DiagnosticName': 'misc-unused-parameters', 'DiagnosticMessage': {'Message': "parameter 'massScalars' is unused", 'FilePath': '/github/workspace/src/RadSuOlson/test_radiation_SuOlson.cpp', 'FileOffset': 3631, 'Replacements': [{'FilePath': '/github/workspace/src/RadSuOlson/test_radiation_SuOlson.cpp', 'Offset': 3631, 'Length': 1, 'ReplacementText': ' /*massScalars*/'}]}, 'Level': 'Warning', 'BuildDirectory': '/github/workspace/build/src/RadSuOlson'}, 
{'DiagnosticName': 'misc-unused-parameters', 'DiagnosticMessage': {'Message': "parameter 'massScalars' is unused", 'FilePath': '/github/workspace/src/RadTophat/test_radiation_tophat.cpp', 'FileOffset': 3817, 'Replacements': [{'FilePath': '/github/workspace/src/RadTophat/test_radiation_tophat.cpp', 'Offset': 3817, 'Length': 1, 'ReplacementText': ' /*massScalars*/'}]}, 'Level': 'Warning', 'BuildDirectory': '/github/workspace/build/src/RadTophat'}]}
```

**Comment by BenWibking** [comment]
@markkrumholz @psharda would either of you be able to review this? It should be very straightforward.

**Comment by markkrumholz** [comment]
> @markkrumholz @psharda would either of you be able to review this? It should be very straightforward.

Will look tomorrow. Today is a holiday in Australia, and I have family in town.

**Review by psharda — APPROVED** [review]

**Pull request merged**
