### PR TITLE
[WIP] set Newton iteration maxIter to 50

### PR DESCRIPTION
**Pull request by chongchonghe**
### Description

We don't need a high value for maxIter since the Newton-Raphson iteration converges fast under the new base variables. We should also minimizing the average/maximal iterations for good performance. 

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [x] I have added a description (see above).
- [x] I have added a link to any related issues see (see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [x] I have tested this PR on my local computer and all tests pass.
- [x] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [ ] I have requested a reviewer for this PR.

### CODE REVIEW

**Comment by BenWibking** [comment]
This is somewhat dangerous, since this assertion does not actually work when running on GPU:
https://github.com/quokka-astro/quokka/blob/3085279a9387e7ebb8adf263a66e0e1747e0c488/src/radiation_system.hpp#L1358

See https://github.com/quokka-astro/quokka/issues/543.

**Comment by chongchonghe** [comment]
> This is somewhat dangerous, since this assertion does not actually work when running on GPU:
> 
> https://github.com/quokka-astro/quokka/blob/3085279a9387e7ebb8adf263a66e0e1747e0c488/src/radiation_system.hpp#L1358
> 
> See #543.

OK, I'll look into that when I get back to work next couple of weeks. I'll leave it here for now with a label "Do not merge".

**Comment by BenWibking** [comment]
> > This is somewhat dangerous, since this assertion does not actually work when running on GPU:
> > https://github.com/quokka-astro/quokka/blob/3085279a9387e7ebb8adf263a66e0e1747e0c488/src/radiation_system.hpp#L1358
> > 
> > See #543.
> 
> OK, I'll look into that when I get back to work next couple of weeks. I'll leave it here for now with a label "Do not merge".

@chongchonghe Can you take a look at this again? I think this is the last thing before the radiation code can be used for production sims.

**Comment by chongchonghe** [comment]
Completed in #716

**Pull request closed without merging**
