### PR TITLE
Fix "Newton-Rasphon iteration failed to converge" bug when tau = 0.

### PR DESCRIPTION
**Pull request by chongchonghe**
### Description

Since we base our Newton-Rasphon iteration on (E_gas, R), where R = tau (4 pi B / c - E), when tau = 0, E is not deducible from R. This causes division-by-zero error and E = NAN, which causes the iteration fail to converge. In this PR, I fixed this issue by enforcing d E_g = 0 when tau_g = 0. Here E_g is the radiation energy of the g'th photon group.

To validate this fix, I modified the ShockMultigroup test to include an extra redundant photon bin where kappa is set to 0.

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [x] I have added a description (see above).
- [x] I have added a link to any related issues see (see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [x] I have added tests for any new physics that this PR adds to the code.
- [ ] I have tested this PR on my local computer and all tests pass.
- [ ] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [ ] I have requested a reviewer for this PR.

### CODE REVIEW

**Review by BenWibking — CHANGES_REQUESTED** [review]
Can you sync your submodules? Those shouldn't be changed in this PR.

**Comment by chongchonghe** [comment]
@BenWibking How can I debug this error on CMake / build? `valarray.hpp:117:17: runtime error: division by zero` . I can't reproduce this error on my macOS or Gadi, even with debug.

**Comment by BenWibking** [comment]
Did you configure with the same CMake options:
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 -DENABLE_ASAN=ON`

**Comment by chongchonghe** [comment]
Somehow the submodules are mismatched and I don't know how to fix them, so I created a new PR #603 to replace this one.

**Pull request closed without merging**
