### PR TITLE
add LLF fallback solver

### LINKED ISSUE #379: fallback to LLF solver
We should add the option to use the Local Lax-Friedrichs (LLF) Riemann solver when doing first-order flux correction.

When doing first-order flux correction, we revert to donor cell fluxes but currently use the same Riemann solver (HLLC). This may be insufficient for flows very close to vacuum, since the positivity-preserving timestep can be extremely small compared to the CFL timestep.

### PR DESCRIPTION
**Pull request by BenWibking**
Uses the Local-Lax Friedrichs (Rusanov) solver as a "fallback" Riemann solver.

Closes https://github.com/quokka-astro/quokka/issues/379.

### CODE REVIEW

**Review by markkrumholz — COMMENTED** [review]
The change to how Riemann solvers are referenced is going to cause conflicts with the MHD branch, since the same changes will need to applied to the HLLD solver in that branch. I'm not sure where @AstroKriel's MHD branch is with respect to the repo, but we might want to have a look just to make sure that there won't be any pain points when we need to integrate these changes with the MHD HLLD solver.

**Comment by BenWibking** [comment]
> The change to how Riemann solvers are referenced is going to cause conflicts with the MHD branch, since the same changes will need to applied to the HLLD solver in that branch. I'm not sure where @AstroKriel's MHD branch is with respect to the repo, but we might want to have a look just to make sure that there won't be any pain points when we need to integrate these changes with the MHD HLLD solver.

The trivial solution is to just add another conditional case to the `if constexpr` statement in `HydroSystem::ComputeFluxes`. I don't think it should be more involved than that.

**Comment by markkrumholz** [comment]
> > The change to how Riemann solvers are referenced is going to cause conflicts with the MHD branch, since the same changes will need to applied to the HLLD solver in that branch. I'm not sure where @AstroKriel's MHD branch is with respect to the repo, but we might want to have a look just to make sure that there won't be any pain points when we need to integrate these changes with the MHD HLLD solver.
> 
> The trivial solution is to just add another conditional case to the `if constexpr` statement in `HydroSystem::ComputeFluxes`. I don't think it should be more involved than that.

OK. I guess that should be done in a separate PR, which will have to happen before @AstroKriel's code can be merged into the main branch.

**Review by markkrumholz — APPROVED** [review]

**Pull request merged**
