### PR TITLE
Ensure EOS.hpp compiles on AMD GPUs

### LINKED ISSUE #308: changes to EOS.hpp broke AMD GPU build
Some mass scalars-related stuff causes a compile error when building for AMD GPUs: https://github.com/quokka-astro/quokka/actions/runs/5232438704/jobs/9447150999?pr=307

### PR DESCRIPTION
**Pull request by psharda**
This hopefully fixes #308

### CODE REVIEW

**Comment by psharda** [comment]
Is there a CI we can add to test if pull requests also build successfully on Setonix (from now on)?

**Comment by BenWibking** [comment]
> Is there a CI we can add to test if pull requests also build successfully on Setonix (from now on)?

We can test if it builds for AMD GPUs: https://github.com/quokka-astro/quokka/pull/307.

Unfortunately, Setonix also has proprietary compilers and libraries from Cray that we can't test without actually manually testing on Setonix.

**Comment by psharda** [comment]
> > Is there a CI we can add to test if pull requests also build successfully on Setonix (from now on)?
> 
> We can test if it builds for AMD GPUs: #307.

So, do I merge #307 into this PR, and see if the `hip.yml` test passes?

**Comment by BenWibking** [comment]
> > > Is there a CI we can add to test if pull requests also build successfully on Setonix (from now on)?
> > 
> > 
> > We can test if it builds for AMD GPUs: #307.
> 
> So, do I merge #307 into this PR, and see if the `hip.yml` test passes?

Yes, that should do it.

**Comment by BenWibking** [comment]
It looks like the AMD compiler has the same compiler bug that Apple Clang has about unused variables. You can just remove the line that sets `CXXFLAGS` in `hip.yml` entirely.

**Comment by BenWibking** [comment]
> It looks like the AMD compiler has the same compiler bug that Apple Clang has about unused variables. You can just remove the line that sets `CXXFLAGS` in `hip.yml` entirely.

See this: https://github.com/quokka-astro/quokka/pull/307/commits/79443a9f7cd32cbfdb71efd1dc0e92bbedbfa68a

**Comment by psharda** [comment]
> It looks like the AMD compiler has the same compiler bug that Apple Clang has about unused variables. You can just remove the line that sets `CXXFLAGS` in `hip.yml` entirely.

Oh lol, before I saw your comment, I changed the .cpp file where the bug was coming from to just use the unused variable.

**Comment by psharda** [comment]
HIP test passed

**Review by BenWibking — APPROVED** [review]
Looks good to me.

**Pull request merged**
