### PR TITLE
enable FPE traps in CI

### LINKED ISSUE #556: compile and run test suite with hipcc + FPE traps on CPU
**Describe the proposal**
The test suite should be compiled with Clang and run automatically as a GitHub Action. This helps us avoid running into problems in production simulations that only appear with Clang-based compilers (such as the AMDGPU compiler).

**Describe alternatives you've considered**
The alternative is to continue to encounter errors that only happen when running on AMD GPUs.

**Additional context**
This is the underlying cause of https://github.com/quokka-astro/quokka/issues/555.

### PR DESCRIPTION
**Pull request by BenWibking**
### Description
Enables signal handling and floating-point exception (FPE) traps for NANs when running the test suite, so it will stop and report an error when NANs are encountered. (This only works on CPUs.)

In order for this to work, we change the signal handling settings back to AMReX defaults. We also have to suppress FPEs when importing `numpy` (see https://github.com/numpy/numpy/issues/20504).

By default, many compilers perform optimizations that assume that floating-point exceptions are disabled, and will often produce spurious FPEs for vectorized code (however, this does not affect the results in any way). There are compiler-specific options to disable this behavior for Intel and Clang.

Note that `AMReX_FPE=ON` only sets the compiler option `-ftrapv` (or similar). We instead add the runtime options `amrex.fpe_trap_invalid=1`, `amrex.fpe_trap_zero=1`, and `amrex.fpe_trap_overflow=1` to the command-line arguments for each test. These options can also be added to the input file (or command line) to debug individual problems.

**Depends on:**
* https://github.com/quokka-astro/quokka/pull/667
* https://github.com/quokka-astro/quokka/pull/668
* https://github.com/quokka-astro/quokka/pull/671

### Related issues
Partially resolves https://github.com/quokka-astro/quokka/issues/556.

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [x] I have added a description (see above).
- [x] I have added a link to any related issues see (see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [x] I have tested this PR on my local computer and all tests pass.
- [x] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [x] I have requested a reviewer for this PR.

### CODE REVIEW

**Review by markkrumholz — COMMENTED** [review]
Code looks fine, but there is a design question we should consider. Producing a NaN is always an error, but producing underflows or overflows may not be. I'm thinking in particular of chemistry, where we have a lot of rate coefficients that take the form rate ~ exp(-T_activation / T_gas), where T_activation is the activation temperature for some reaction. At low T_gas this will underflow and give a rate coefficient of exactly zero, but that is the desired behavior. Similarly, for multigroup radiation we may well have groups where the exponential term in the Planck function underflows to zero in low-temperature parts of the simulation domain, and that is again the desired behavior. Thus I'm worried that a FPE that triggers on underflow or overflow may be too sensitive. Thoughts on this issue?

**Comment by BenWibking** [comment]
> Code looks fine, but there is a design question we should consider. Producing a NaN is always an error, but producing underflows or overflows may not be. I'm thinking in particular of chemistry, where we have a lot of rate coefficients that take the form rate ~ exp(-T_activation / T_gas), where T_activation is the activation temperature for some reaction. At low T_gas this will underflow and give a rate coefficient of exactly zero, but that is the desired behavior. Similarly, for multigroup radiation we may well have groups where the exponential term in the Planck function underflows to zero in low-temperature parts of the simulation domain, and that is again the desired behavior. Thus I'm worried that a FPE that triggers on underflow or overflow may be too sensitive. Thoughts on this issue?

By design, it *should* only trap on overflow, not underflow.

However, I think the underlying compiler option this turns on is not actually equivalent to the runtime behavior that is enabled with `amrex.fpe_trap_invalid`, `amrex.fpe_trap_overflow` and `amrex.fpe_trap_zero` (division-by-zero), so I need to re-work this PR and test it explicitly.

**Comment by BenWibking** [comment]
~~The Intel compiler produces spurious FPEs for optimized code, will have to disable for that.~~

Ref: https://stackoverflow.com/questions/52644343/replacing-01-with-02-intel-compiler-option-leads-to-throwing-fpe-at-small/52652657#52652657

**Comment by BenWibking** [comment]
May need to turn on `-ffp-exception-behavior=maytrap` with Clang compilers (i.e., for Intel and macOS tests): https://clang.llvm.org/docs/UsersManual.html#cmdoption-ffp-exception-behavior

**Comment by BenWibking** [comment]
This is currently failing because of a division by zero in matplotlib:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=1, subcode=0x1e611800)
  * frame #0: 0x0000000107b0636c _multiarray_umath.cpython-312-darwin.so`longdouble_true_divide + 364
    frame #1: 0x00000001018b1aac Python`binary_op1 + 88
    frame #2: 0x00000001018b1e9c Python`PyNumber_TrueDivide + 32
    frame #3: 0x00000001019c3988 Python`_PyEval_EvalFrameDefault + 53224
    frame #4: 0x00000001019b6730 Python`PyEval_EvalCode + 184
    frame #5: 0x00000001019b2fe4 Python`builtin_exec + 416
    frame #6: 0x000000010191e4b8 Python`cfunction_vectorcall_FASTCALL_KEYWORDS + 92
    frame #7: 0x00000001019c2f20 Python`_PyEval_EvalFrameDefault + 50560
    frame #8: 0x00000001018cf430 Python`object_vacall + 212
    frame #9: 0x00000001018cf310 Python`PyObject_CallMethodObjArgs + 104
    frame #10: 0x00000001019f5fc0 Python`PyImport_ImportModuleLevelObject + 996
    frame #11: 0x00000001019b1940 Python`builtin___import__ + 172
    frame #12: 0x000000010191e4b8 Python`cfunction_vectorcall_FASTCALL_KEYWORDS + 92
    frame #13: 0x00000001019c2f20 Python`_PyEval_EvalFrameDefault + 50560
    frame #14: 0x00000001018cf430 Python`object_vacall + 212
    frame #15: 0x00000001018cf310 Python`PyObject_CallMethodObjArgs + 104
    frame #16: 0x00000001019f5fc0 Python`PyImport_ImportModuleLevelObject + 996
    frame #17: 0x00000001019b1940 Python`builtin___import__ + 172
    frame #18: 0x000000010191e4b8 Python`cfunction_vectorcall_FASTCALL_KEYWORDS + 92
    frame #19: 0x00000001019c2f20 Python`_PyEval_EvalFrameDefault + 50560
    frame #20: 0x00000001018cf430 Python`object_vacall + 212
    frame #21: 0x00000001018cf310 Python`PyObject_CallMethodObjArgs + 104
    frame #22: 0x00000001019f5fc0 Python`PyImport_ImportModuleLevelObject + 996
    frame #23: 0x00000001019b1940 Python`builtin___import__ + 172
    frame #24: 0x000000010191e4b8 Python`cfunction_vectorcall_FASTCALL_KEYWORDS + 92
    frame #25: 0x00000001018ce81c Python`_PyObject_CallFunctionVa + 152
    frame #26: 0x00000001018ce778 Python`PyObject_CallFunction + 60
    frame #27: 0x00000001019f5a00 Python`PyImport_Import + 192
    frame #28: 0x00000001019f58e4 Python`PyImport_ImportModule + 60
    frame #29: 0x000000010000d124 test_advection`_import_array() at __multiarray_api.h:1482:21
    frame #30: 0x000000010000ce2c test_advection`matplotlibcpp::detail::_interpreter::import_numpy(this=0x0000000100510000) at matplotlibcpp.h:126:3
    frame #31: 0x000000010000b9b4 test_advection`matplotlibcpp::detail::_interpreter::_interpreter(this=0x0000000100510000) at matplotlibcpp.h:160:3
    frame #32: 0x000000010000b8d8 test_advection`matplotlibcpp::detail::_interpreter::_interpreter(this=0x0000000100510000) at matplotlibcpp.h:141:2
    frame #33: 0x000000010000a764 test_advection`matplotlibcpp::detail::_interpreter::get() at matplotlibcpp.h:103:23
    frame #34: 0x000000010000a43c test_advection`_object* matplotlibcpp::get_array<double>(v=size=400) at matplotlibcpp.h:320:2
    frame #35: 0x000000010000a1cc test_advection`bool matplotlibcpp::plot<double>(x=size=400, y=size=400, keywords=size=1) at matplotlibcpp.h:375:21
    frame #36: 0x000000010000529c test_advection`matplotlibcpp::plot(x=size=400, y=size=400, keywords=size=1) at matplotlibcpp.h:1870:9
    frame #37: 0x00000001000046d8 test_advection`AdvectionSimulation<SawtoothProblem>::computeReferenceSolution(this=0x000000016fdfdfb8, ref=0x000000016fdfd1b8, dx=0x000000016fdfd170, prob_lo=0x000000016fdfd168, prob_hi=0x000000016fdfd160) at test_advection.cpp:110:3
```

**Comment by BenWibking** [comment]
FPEs do not seem to work on Linux ARM64.

**Comment by BenWibking** [comment]
There were several divide by zero corner cases in `HydroSystem::EnforceLimits`. Those changes have been moved to a separate PR.

**Comment by BenWibking** [comment]
The Intel compiler still gives a different result than every other compiler :shrug:

**Comment by BenWibking** [comment]
Useful compiler options:
* https://clang.llvm.org/docs/UsersManual.html#cmdoption-ffp-exception-behavior
* https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-fsignaling-nans

**Comment by BenWibking** [comment]
Two longstanding issues have been fixed:
* https://github.com/quokka-astro/quokka/pull/671
* https://github.com/quokka-astro/quokka/pull/668

**Comment by BenWibking** [comment]
Very strange error in RadTube with `-DCMAKE_BUILD_TYPE=Debug` with Intel OneAPI compiler 2024.0:
```
Thread 1 "test_radiation_" received signal SIGFPE, Arithmetic exception.
0x00000000005525ad in HydroSystem<TubeProblem>::FlattenShocks<(FluxDir)0>(amrex::MultiFab const&, amrex::MultiFab const&, amrex::MultiFab const&, amrex::MultiFab const&, amrex::MultiFab&, amrex::MultiFab&, int, int)::{lambda(int, int, int, int, int)#1}::operator()(int, int, int, int, int) const (this=0x7fffffff0aa8, bx=0, i_in=32, j_in=0, k_in=0, n=0)
    at /home1/02661/bwibking/quokka/src/hydro_system.hpp:682
682                     const double new_a_plus = chi_ijk * a_plus + (1. - chi_ijk) * a_mean;
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.34-60.el9_2.7.x86_64 intel-oneapi-mpi-2021.11-2021.11.0-49493.x86_64 intel-oneapi-openmp-2024.0-2024.0.0-49819.x86_64 libibverbs-44.0-2.el9.x86_64 libnl3-3.7.0-1.el9.x86_64 libpsm2-11.2.230-1.el9.x86_64 libuuid-2.37.4-11.el9_2.x86_64 numactl-libs-2.0.14-9.el9.x86_64
(gdb) p a_plus
$1 = nan(0x080000001)
(gdb) p *(double (*)[35])x1LeftState.arr_
$7 = {1, 1, 1.0031302901828618, 1.0087967118286469, 1.0138736005001696, 1.0189852692678643, 1.0241321183987466,
  1.0293145129741614, 1.0345328216040177, 1.0397874239243379, 1.0450787080568562, 1.0504070706090192, 1.0557729166739847,
  1.0611766598306227, 1.0666187221435153, 1.0720995341629562, 1.0776195349249502, 1.083179171951216, 1.0887789012491815,
  1.0944191873119888, 1.1001005031184901, 1.105823330133251, 1.1115881583065474, 1.1173954860743678, 1.1232458203584135,
  1.1291396765660953, 1.135077578590538, 1.1410600588105777, 1.1470876580907616, 1.1531609257813504, 1.159280419718314,
  1.1654467062233367, 1.1716603601038131, 1.1779219646528512, nan(0x080000001)}
```

~~Is the number of ghost cells for this kernel set incorrectly?~~ No.

**Comment by BenWibking** [comment]
~~We have the same issue as this: https://github.com/numpy/numpy/issues/20504.~~ Fixed.

**Comment by BenWibking** [comment]
These GPU tests fail:
```
The following tests FAILED:
	 30 - BinaryOrbitCIC (Failed)
	 37 - PopIII (Failed)
	 39 - StarCluster (Failed)
```

**Comment by BenWibking** [comment]
Last remaining test failures on avatargpu:
```
The following tests FAILED:
	 37 - PopIII (Failed)
	 39 - StarCluster (Failed)
```

It appears to fail when reading the turbulence driving field:
```
CUDA initialized with 1 device.
AMReX (24.06) initialized
Successfully read inputs file ... 
Using derived variables:
	log_density

Creating new distribution map on level: 0
Initializing turbulence data...
data_file: zdrv.hdf5.
Erroneous arithmetic operation
See Backtrace.0 file for details
```

It's caused by an FPE inside the HDF5 library :/
See https://github.com/HDFGroup/hdf5/issues/3831.

**Comment by BenWibking** [comment]
Backtrace:
```
 0: ../build/src/StarCluster/star_cluster() [0x628bc0]
    amrex::BLBackTrace::handler(int) at ??:?

 1: /lib64/libc.so.6(+0x54db0) [0x7f1d04454db0]

 2: /home/bwibking/spack-avatargpu/opt/spack/linux-rocky9-cascadelake/gcc-11.4.1/hdf5-1.14.3-ippzz4bnd6azzbxlhirmsmyfk4akb6pe/lib/libhdf5.so.310(H5T__init_native_float_types+0xbc0) [0x7f1d04ec62d0]
    ?? ??:0

 3: /home/bwibking/spack-avatargpu/opt/spack/linux-rocky9-cascadelake/gcc-11.4.1/hdf5-1.14.3-ippzz4bnd6azzbxlhirmsmyfk4akb6pe/lib/libhdf5.so.310(H5T_init+0x37) [0x7f1d04e48987]
    ?? ??:0

 4: /home/bwibking/spack-avatargpu/opt/spack/linux-rocky9-cascadelake/gcc-11.4.1/hdf5-1.14.3-ippzz4bnd6azzbxlhirmsmyfk4akb6pe/lib/libhdf5.so.310(H5VL_init_phase2+0x133) [0x7f1d04ee5943]
    ?? ??:0

 5: /home/bwibking/spack-avatargpu/opt/spack/linux-rocky9-cascadelake/gcc-11.4.1/hdf5-1.14.3-ippzz4bnd6azzbxlhirmsmyfk4akb6pe/lib/libhdf5.so.310(H5_init_library+0x28b) [0x7f1d04c1d72b]
    ?? ??:0

 6: /home/bwibking/spack-avatargpu/opt/spack/linux-rocky9-cascadelake/gcc-11.4.1/hdf5-1.14.3-ippzz4bnd6azzbxlhirmsmyfk4akb6pe/lib/libhdf5.so.310(H5open+0x29) [0x7f1d04c1df59]
    ?? ??:0

 7: ../build/src/StarCluster/star_cluster() [0x5632c4]
    initialize_turbdata(turb_data&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) at ??:?

 8: ../build/src/StarCluster/star_cluster() [0x438690]
    RadhydroSimulation<StarCluster>::preCalculateInitialConditions() at ??:?
```
It traps a `NaN` here.

**Comment by BenWibking** [comment]
@markkrumholz Can you review this PR?

**Review by markkrumholz — APPROVED** [review]

**Pull request merged**
