### PR TITLE
PPL-opacity branch starting from PR #667

### PR DESCRIPTION
**Pull request by chongchonghe**
### Description

Merge the changes in #678 into the development branch at PR #667 , right before PR #611 . This is to isolate the portion of the code brought in by #611 from branch #678 . 

Just for testing purpose. DO NOT MERGE YET. 

### Related issues
#679 and #678 

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [ ] I have added a description (see above).
- [ ] I have added a link to any related issues see (see above).
- [ ] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [ ] I have tested this PR on my local computer and all tests pass.
- [ ] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [ ] I have requested a reviewer for this PR.

### CODE REVIEW

**Comment by chongchonghe** [comment]
`GPU, 3D (gcc, nvcc)` failed due to `/tmp/bwibking/_work/1/s/src/matplotlibcpp.h:15:10: fatal error: Python.h: No such file or directory` 
https://dev.azure.com/quokka-code/quokka-CI/_build/results?buildId=10714&view=logs&j=655dacad-9e02-5f72-e0cf-043ebfb7cecc&t=e95f4446-ac23-5f52-1703-4ff6a9656172&l=1281

**Comment by BenWibking** [comment]
> `GPU, 3D (gcc, nvcc)` failed due to `/tmp/bwibking/_work/1/s/src/matplotlibcpp.h:15:10: fatal error: Python.h: No such file or directory` https://dev.azure.com/quokka-code/quokka-CI/_build/results?buildId=10714&view=logs&j=655dacad-9e02-5f72-e0cf-043ebfb7cecc&t=e95f4446-ac23-5f52-1703-4ff6a9656172&l=1281

The GPU tests are run without Python enabled. Did you add a Python header include or use matplotlibcpp without wrapping it in `#ifdef HAVE_PYTHON`?

**Comment by chongchonghe** [comment]
Abandoned this PR and focus on #678 instead.

**Pull request closed without merging**
