### PR TITLE
Update GPU CI timeout

### LINKED ISSUE #415: GPU CI fails (need to increase GPU CI timeout to 90 minutes)
**Describe the bug**
The GPU tests time out and fail because they hit the maximum walltime of 60 minutes.

**To Reproduce**
1. Run the GPU test suite on avatargpu
3. After 60 minutes, see timeout error

**Additional context**
Our test suite has grown increasingly lengthy. For some test problems, we might be able to reduce the number of timesteps we take by increasing the CFL number or simulating for less time. A few problems take longer to run on the GPU than on the CPU due to kernel launch overheads for essentially 1D/single-zone problems.

The easiest fix is to just increase the maximum time we are willing to wait for the test suite to complete on the GPU node.

### PR DESCRIPTION
**Pull request by BenWibking**
Set timeout to 90 minutes (increased from the default value of 60 minutes).

Fixes https://github.com/quokka-astro/quokka/issues/415.

### CODE REVIEW

**Comment by BenWibking** [comment]
@psharda Can you approve?

**Review by psharda — APPROVED** [review]

**Pull request merged**
