### PR TITLE
added Microphysics as a submodule for Quokka

### PR DESCRIPTION
**Pull request by psharda**
This PR will add Microphysics as a submodule for Quokka.

### CODE REVIEW

**Comment by BenWibking** [comment]
Ah, we actually need to wait for this: https://github.com/AMReX-Astro/Microphysics/issues/1103

**Comment by psharda** [comment]
Right, so how do we do this

**Comment by psharda** [comment]
Also, Mike will merge my cmake PR in `Microphysics/development`. So, it will not be available in the `main` branch of Microphysics (the one we are adding as a submodule in quokka) until the start of the next month (when he merges `development` into `main`

**Comment by BenWibking** [comment]
I would add your Microphysics branch as a submodule, then create a new test problem in Quokka to build with the network.

**Comment by BenWibking** [comment]
That's ok, we can point the submodule to any Microphysics branch we want.

**Comment by BenWibking** [comment]
We'll need to add the same Microphysics *.cpp files to the Quokka CMakeLists.txt file that you added to the unit test CMakeLists.txt:
```
add_executable(test_microphysics
    main.cpp
    ${CMAKE_SOURCE_DIR}/interfaces/eos_data.cpp
    ${CMAKE_SOURCE_DIR}/interfaces/network_initialization.cpp
    ${CMAKE_SOURCE_DIR}/EOS/primordial_chem/actual_eos_data.cpp
    ${CMAKE_BINARY_DIR}/extern_parameters.cpp
    )
```

So it might make sense to create (in the Microphysics root CMakeLists.txt) a variable to store this list of files that we can then reference in the Quokka CMakeLists.txt.

**Comment by psharda** [comment]
> We'll need to add the same Microphysics *.cpp files to the Quokka CMakeLists.txt file that you added to the unit test CMakeLists.txt:
> 
> ```
> add_executable(test_microphysics
>     main.cpp
>     ${CMAKE_SOURCE_DIR}/interfaces/eos_data.cpp
>     ${CMAKE_SOURCE_DIR}/interfaces/network_initialization.cpp
>     ${CMAKE_SOURCE_DIR}/EOS/primordial_chem/actual_eos_data.cpp
>     ${CMAKE_BINARY_DIR}/extern_parameters.cpp
>     )
> ```
> 
> So it might make sense to create (in the Microphysics root CMakeLists.txt) a variable to store this list of files that we can then reference in the Quokka CMakeLists.txt.

But we use these files in the burn_cell_primordial_chem test, and not in Microphysics root. If we create a variable for these files in Microphysics root, can we just call it in CMakeLists for burn_cell_primordial_chem?

**Comment by psharda** [comment]
> That's ok, we can point the submodule to any Microphysics branch we want.

Added the specific branch in the submodule call.

**Comment by BenWibking** [comment]
> > We'll need to add the same Microphysics *.cpp files to the Quokka CMakeLists.txt file that you added to the unit test CMakeLists.txt:
> > ```
> > add_executable(test_microphysics
> >     main.cpp
> >     ${CMAKE_SOURCE_DIR}/interfaces/eos_data.cpp
> >     ${CMAKE_SOURCE_DIR}/interfaces/network_initialization.cpp
> >     ${CMAKE_SOURCE_DIR}/EOS/primordial_chem/actual_eos_data.cpp
> >     ${CMAKE_BINARY_DIR}/extern_parameters.cpp
> >     )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So it might make sense to create (in the Microphysics root CMakeLists.txt) a variable to store this list of files that we can then reference in the Quokka CMakeLists.txt.
> 
> But we use these files in the burn_cell_primordial_chem test, and not in Microphysics root. If we create a variable for these files in Microphysics root, can we just call it in CMakeLists for burn_cell_primordial_chem?

Yes, it can be used in both the unit test CMakeLists.txt and in the Quokka CMakeLists.txt. A win-win :)

**Comment by BenWibking** [comment]
Quokka will also need a variable for the include directories. That can be re-used by the unit test CMakeLists.txt as well.

**Comment by psharda** [comment]
> > > We'll need to add the same Microphysics *.cpp files to the Quokka CMakeLists.txt file that you added to the unit test CMakeLists.txt:
> > > ```
> > > add_executable(test_microphysics
> > >     main.cpp
> > >     ${CMAKE_SOURCE_DIR}/interfaces/eos_data.cpp
> > >     ${CMAKE_SOURCE_DIR}/interfaces/network_initialization.cpp
> > >     ${CMAKE_SOURCE_DIR}/EOS/primordial_chem/actual_eos_data.cpp
> > >     ${CMAKE_BINARY_DIR}/extern_parameters.cpp
> > >     )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So it might make sense to create (in the Microphysics root CMakeLists.txt) a variable to store this list of files that we can then reference in the Quokka CMakeLists.txt.
> > 
> > 
> > But we use these files in the burn_cell_primordial_chem test, and not in Microphysics root. If we create a variable for these files in Microphysics root, can we just call it in CMakeLists for burn_cell_primordial_chem?
> 
> Yes, it can be used in both the unit test CMakeLists.txt and in the Quokka CMakeLists.txt. A win-win :)

I did this, created a variable called `primordial_chem_sources` for all these files in Microphysics root, and then called them in the burn_cell_primordial_chem's CMakeLists using `add_executable(test ${primordial_chem_sources})`. I get this error during `make`: 

Undefined symbols for architecture x86_64:
"_main", referenced from:
    implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64

**Comment by BenWibking** [comment]
You still need to include `main.cpp` within the unit test `add_executable` command.

**Comment by psharda** [comment]
In the burn_cell_primordial_chem CMakeLists, I did `add_executable(test_burn_cell_primordial_chem main.cpp ${primordial_chem_sources})`

At the end of root CMakeLists, I define:
set(primordial_chem_sources
    ${CMAKE_SOURCE_DIR}/interfaces/eos_data.cpp
    ${CMAKE_SOURCE_DIR}/interfaces/network_initialization.cpp
    ${CMAKE_SOURCE_DIR}/EOS/primordial_chem/actual_eos_data.cpp
    ${CMAKE_BINARY_DIR}/extern_parameters.cpp
   )
   
   
I now get all the unreferenced errors  :  "_temperature", referenced from:
      burn_cell_c() in main.cpp.o

**Comment by psharda** [comment]
Tyring it with `target_sources` and `source_group`

**Comment by psharda** [comment]
Nope, still get all the linking errors.

**Comment by psharda** [comment]
All the solutions I find on stackoverflow suggest using `file(GLOB...)` to store multiple source files in the same variable. But then `GLOB` is not recommended by cmake developers.

**Comment by BenWibking** [comment]
> All the solutions I find on stackoverflow suggest using `file(GLOB...)` to store multiple source files in the same variable. But then `GLOB` is not recommended by cmake developers.

It should, in principle, work the same whether it's in a variable or directly listed, e.g.: https://stackoverflow.com/questions/37225229/adding-sources-to-a-list-variable-in-cmake-vs-directly-in-add-executable.  Can you copy and paste the differences between the verbose make outputs?

**Comment by BenWibking** [comment]
Maybe there's some subtle issue with variable scope. Can you try defining the variable in the `burn_cell_primordial_chem/CMakeLists.txt` itself just to make sure that works?

**Comment by psharda** [comment]
> Maybe there's some subtle issue with variable scope. Can you try defining the variable in the `burn_cell_primordial_chem/CMakeLists.txt` itself just to make sure that works?

yeah that works.

**Comment by BenWibking** [comment]
> > Maybe there's some subtle issue with variable scope. Can you try defining the variable in the `burn_cell_primordial_chem/CMakeLists.txt` itself just to make sure that works?
> 
> yeah that works.

Gahh, ok. Some weird CMake thing is going on then when it's defined in a different file :(

Unfortunately, I think we have to figure out what it is, since we need the ability to do this to integrate with the existing way Quokka builds are done.

**Comment by psharda** [comment]
I posted a question on SO

**Comment by psharda** [comment]
There is a `PARENT_SCOPE` option for setting variables in cmake that can make the variable available one directory up from where it's defined. But, it does not seem to work two (or more) directories up.

**Comment by BenWibking** [comment]
> There is a `PARENT_SCOPE` option for setting variables in cmake that can make the variable available one directory up from where it's defined. But, it does not seem to work two (or more) directories up.

This is the opposite case, no? I think the variable should be defined in the root CMakeLists.txt, and then used from the (nested) subdirectories.

**Comment by psharda** [comment]
I might have found a solution!

**Comment by psharda** [comment]
Okay, it works now. I learned that the content in CMakeLists has to be ordered? I was using `set` after `add_subdirectory` in the root CMakeLists, which is why the variable being set was not visible in the child scope (aka the subdirectory). Once I set the variable first and then added the subdirectory, it was available in the CMakeLists in burn_cell_primordial_chem

**Comment by psharda** [comment]
Why do 2 of the tests fail?

**Comment by BenWibking** [comment]
> Why do 2 of the tests fail?

I broke the test machine that the arm64 tests run on :( I'll fix it.

**Comment by psharda** [comment]
Haha no worries. 
What else needs to be done before we can approve this PR?

**Comment by BenWibking** [comment]
Can you check what commit the Microphysics submodule points to? On the GitHub 'files changed' tab, it shows a commit from before your Microphysics PR was merged, so CMakeLists.txt is not present there.

**Comment by BenWibking** [comment]
Nothing other than checking the commit hash for this PR. We can do another PR to make changes to the CMakeLists.txt files in Quokka, as well as adding a test problem in Quokka.

**Comment by psharda** [comment]
How about now?

**Comment by BenWibking** [comment]
Looks good now.

**Review by BenWibking — APPROVED** [review]

**Pull request merged**
