### PR TITLE
add equations to docs

### PR DESCRIPTION
**Pull request by BenWibking**
### Description
This adds the complete set of equations that are solved by Quokka to the documentation.

### Related issues
N/A

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [x] I have added a description (see above).
- [ ] I have added a link to any related issues see (see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [ ] I have tested this PR on my local computer and all tests pass.
- [ ] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [x] I have requested a reviewer for this PR.

### CODE REVIEW

**Comment by BenWibking** [comment]
The equations render like this:

Screenshot 2024-07-30 232530

**Comment by BenWibking** [comment]
@chongchonghe @markkrumholz I am not sure how to write the radiation energy update for the auxiliary internal energy. It is not $\sum_g G^0_g$, as written above, since that includes work contributions... any ideas?

**Comment by markkrumholz** [comment]
In practice we only use the auxiliary internal energy during the hydro update stage, so in some sense what you have written is technically correct, with no radiation terms at all on the RHS. The way radiation terms get incorporated is when the internal energy gets recomputed after the radiation stage. But I think it might actually be more sensible if we are trying to summarize the equations to omit the auxiliary internal energy equation, and instead think of that as simply an alternative numerical method for solving the actual energy equation. That is, the fundamental equations we are solving are the conservation equations, but we use two possible numerical methods to do so, one of which involves solving the auxiliary internal energy equation during the hydro stage only.

**Comment by BenWibking** [comment]
> In practice we only use the auxiliary internal energy during the hydro update stage, so in some sense what you have written is technically correct, with no radiation terms at all on the RHS. The way radiation terms get incorporated is when the internal energy gets recomputed after the radiation stage. But I think it might actually be more sensible if we are trying to summarize the equations to omit the auxiliary internal energy equation, and instead think of that as simply an alternative numerical method for solving the actual energy equation. That is, the fundamental equations we are solving are the conservation equations, but we use two possible numerical methods to do so, one of which involves solving the auxiliary internal energy equation during the hydro stage only.

That is not quite true. I implemented the cooling routines ($\mathcal{H-C}$) such that they also update the auxiliary internal energy.

To be consistent, I had originally designed the radiation update to do likewise, but I lost track of what the current version of the code does in this respect.

(This is also what Castro does: https://amrex-astro.github.io/Castro/docs/Hydrodynamics.html#internal-energy-and-temperature)

I've updated the equations above to show this.

**Comment by markkrumholz** [comment]
OK, not sure what @chongchonghe is doing here either. I think the method you implemented originally does not work with our new relativistically-correct formulation, because in this formulation you can't neatly divide internal and kinetic energy. They get mixed at order v/c. I do not recall what @chongchonghe wound up doing about that.

**Comment by BenWibking** [comment]
> OK, not sure what @chongchonghe is doing here either. I think the method you implemented originally does not work with our new relativistically-correct formulation, because in this formulation you can't neatly divide internal and kinetic energy. They get mixed at order v/c. I do not recall what @chongchonghe wound up doing about that.

I think we can just add $\Delta S_{\text{rad}} = \int_{t_0}^{t_0 + \Delta t} S_{\text{rad}} \ dt = [ E_{gas}(t_0 + \Delta t) - KE(t_0 + \Delta t) ] - [ E_{gas}(t_0) - KE(t_0) ]$ to the auxiliary internal energy, right?

**Comment by BenWibking** [comment]
Maybe we should add a Mach 50 radiative shock test problem to ensure we are doing this right.

**Comment by markkrumholz** [comment]
I agree that your expression has to be correct by construction. But I guess my more basic issue is how the internal energy update interacts with the radiation update within a timestep. My thought was that you only used the internal energy during the hydro step, and that you decided whether to use the internal energy computed separately or just use the total energy, all prior to starting the radiation substep. And then you recompute the internal energy from the total energy and the start of the next hydro substep -- in which case modifications you make to the internal energy during the radiation substep have no effect. So I guess I'm wrong about the ordering somewhere. So where does internal energy that is updated during the radiation substep actually get used?

**Comment by BenWibking** [comment]
> I agree that your expression has to be correct by construction. But I guess my more basic issue is how the internal energy update interacts with the radiation update within a timestep. My thought was that you only used the internal energy during the hydro step, and that you decided whether to use the internal energy computed separately or just use the total energy, all prior to starting the radiation substep. And then you recompute the internal energy from the total energy and the start of the next hydro substep -- in which case modifications you make to the internal energy during the radiation substep have no effect. So I guess I'm wrong about the ordering somewhere. So where does internal energy that is updated during the radiation substep actually get used?

The auxiliary internal energy and total energy are only synchronized after each hydro RK stage. So there is no sync at the start of the next hydro step. As it is done now, if there is a perturbation to the internal energy that is not reflected in the auxiliary internal energy, both the advection of auxiliary internal energy (due to the $F_{\rho X_n}$ flux term) in the RK stage 1 step and the next sync (at the end of the same hydro RK stage 1 update) will use inconsistent values of the auxiliary internal energy and total energy in determining whether and how to sync up.

**Comment by BenWibking** [comment]
> And then you recompute the internal energy from the total energy and the start of the next hydro substep

The auxiliary internal energy is never unconditionally replaced by the total energy. It is always conditionally sync'd:
https://github.com/quokka-astro/quokka/blob/725c343e537527c75aafdf15d94ec3ada2497968/src/hydro/hydro_system.hpp#L841

Therefore, there is always the possibility that a perturbation to the total energy will cause the sync direction to change. So the auxiliary internal energy must always be kept consistent when adding energy source terms.

**Comment by markkrumholz** [comment]
Ok, so I think we maybe need to change that. Once you go to a relativistically correct formulation of RHD, you can no longer sensibly separate the terms that apply to internal versus total energy. So I think we may need to sync at the end of the hydro and then just ignore the internal energy during the radiation substep. I don’t think there is a sensible way to write an internal energy equation for radiation that is also relativistically correct.

**Comment by chongchonghe** [comment]
The precise update of the internal energy in the radiation-matter coupling step is this:

``` math
\begin{gather}
\Delta (\rho \vec{v}) = -\sum_g \Delta \vec{F}_g \\
S_{\rm rad} = \sum_g c G_g^0 = - 4 \pi \chi_{0 P} B + c \sum_g \chi_{0E,g} E_g - c^{-1} \sum_g \chi_{0F,g} v^i F_g^i \\
\Delta (\rho e) = S_{\rm rad} \Delta t - \frac{1}{2} \Delta \left(\rho v^2 \right) 
\end{gather}
```

Not sure how you would write this into one single equation.

For infinitesimal time step, those work term cancels, so you get the simple formula

``` math
\Delta (\rho e) = \left( - 4 \pi \chi_{0 P} B + c \sum_g \chi_{0E,g} E_g \right) \Delta t
```

so, in principle, you can write it as a differential equation, but that would hide how exact we solve those equations.

**Comment by chongchonghe** [comment]
@BenWibking Do you want to update the docs to reflect that? All you wrote in the current PR is correct, and the only thing you need to add is exactly how $S_{\rm rad}$ is defined. The simple way to say it is $S_{\rm rad} = - 4 \pi \chi_{0 P} B + c \sum_g \chi_{0E,g} E_g$, although we solved the whole matter-radiation coupling differently: we include the work ($v/c$) term in the source when updating the gas total energy, then subtract the update of the kinetic energy from the total energy, and what remains is the update in internal energy.

**Comment by BenWibking** [comment]
I would prefer to leave it as is, but we could specify that the time derivative $S_{\text{rad}}$ is never computed, only $\Delta S_{\text{rad}} = \int \sum c G^0_g \ dt - \frac{1}{2} \Delta \left(\rho v^2 \right)$ is computed.

An analogous integral over the timestep is also used in practice for, e.g., the gravitational work term.

**Comment by BenWibking** [comment]
Ok, I am happy with this now. @chongchonghe does this look ok?

**Review by chongchonghe — APPROVED** [review]

**Pull request merged**
